using System.Collections.Generic;
using UnityEngine;

namespace BomBomLemon.Game.Topics
{
    [CreateAssetMenu(fileName = "TopicDatabase", menuName = "BomBom Lemon/Topic Database", order = 1)]
    public class TopicDatabase : ScriptableObject
    {
        [SerializeField] private List<Topic> topics = new();

        public IReadOnlyList<Topic> Topics => topics;

        public Topic GetRandom()
        {
            if (topics.Count == 0) return FallbackTopic();
            return topics[Random.Range(0, topics.Count)];
        }

        static Topic FallbackTopic() => new(
            "好きな食べ物の甘さ", "甘くない", "めちゃ甘い", "塩昆布", "砂糖たっぷりスイーツ",
            "Sweetness of your fav food", "Not sweet", "Extremely sweet", "Salted kelp", "Super sugary dessert"
        );

        [ContextMenu("Load Default Japanese Topics")]
        void LoadDefaultTopics()
        {
            topics = new List<Topic>
            {
                // 1
                new("誕生日にもらって嬉しいもの",
                    "全く嬉しくない", "最高に嬉しい",
                    "500円クオカード", "ハワイ旅行ペア券",
                    "Things you're happy to receive for your birthday",
                    "Not happy at all", "Overjoyed",
                    "A 500-yen gift card", "A couples trip to Hawaii"),
                // 2
                new("空腹のときに食べたいもの",
                    "食欲ゼロ", "最高においしい",
                    "賞味期限切れガム", "高級焼肉食べ放題",
                    "Things you want to eat when starving",
                    "Zero appetite", "Absolutely delicious",
                    "Expired chewing gum", "All-you-can-eat wagyu beef"),
                // 3
                new("夏に涼しくなれるもの・こと",
                    "全然涼しくない", "極限まで涼しい",
                    "うちわ1回あおぐ", "プール付きの別荘",
                    "Things that cool you down in summer",
                    "No coolness at all", "Perfectly refreshed",
                    "One wave of a paper fan", "A villa with a private pool"),
                // 4
                new("子どものころに欲しかったもの",
                    "全然欲しくなかった", "死ぬほど欲しかった",
                    "消しゴムのかす", "ゲーム機全部そろえる",
                    "Things you wanted as a child",
                    "Didn't want at all", "Desperately wanted",
                    "Eraser shavings", "Every game console ever made"),
                // 5
                new("旅行先として行きたい場所",
                    "絶対行きたくない", "今すぐ行きたい",
                    "近所の公園", "モルディブのリゾート",
                    "Places you want to visit as a travel destination",
                    "Never want to go", "Want to go right now",
                    "The park next door", "A Maldives resort"),
                // 6
                new("疲れたときに癒されるもの・こと",
                    "全然癒されない", "完全に癒される",
                    "深呼吸1回だけ", "温泉旅館に1泊",
                    "Things that heal you when you're exhausted",
                    "Not relaxing at all", "Fully restored",
                    "Just one deep breath", "One night at a hot spring inn"),
                // 7
                new("朝起きるのが楽しみになるもの",
                    "全然楽しみじゃない", "最高に楽しみ",
                    "水道水だけある", "給料日の朝",
                    "Things that make you excited to wake up",
                    "Dread waking up", "Can't wait to get up",
                    "Just tap water waiting", "Payday morning"),
                // 8
                new("無人島に持っていったら役立つもの",
                    "全く役に立たない", "命が救われる",
                    "革靴とネクタイ", "衛星電話と救急セット",
                    "Things useful to bring to a deserted island",
                    "Completely useless", "Life-saving",
                    "Leather shoes and a tie", "A satellite phone and first-aid kit"),
                // 9
                new("友達に紹介したいもの・こと",
                    "紹介したくない", "絶対紹介したい",
                    "近所のコンビニ", "人生変わったお店",
                    "Things you want to recommend to friends",
                    "Would never recommend", "Must share with everyone",
                    "The convenience store nearby", "A place that changed my life"),
                // 10
                new("寒い冬に温まれるもの・こと",
                    "全然温まらない", "芯まで温まる",
                    "薄手の靴下1枚", "露天風呂付きの部屋",
                    "Things that warm you up in cold winter",
                    "No warmth at all", "Warm to the core",
                    "One thin pair of socks", "A room with an outdoor hot spring"),
                // 11
                new("お腹が痛いときに助かるもの",
                    "全然助からない", "すぐ楽になる",
                    "深呼吸するだけ", "よく効く整腸剤",
                    "Things that help when you have a stomachache",
                    "No help at all", "Instant relief",
                    "Just deep breathing", "Effective digestive medicine"),
                // 12
                new("子どもに人気がありそうなもの",
                    "子どもが嫌がる", "取り合いになる",
                    "算数の教科書", "遊び放題のテーマパーク",
                    "Things that seem popular with kids",
                    "Kids hate it", "Kids fight over it",
                    "A math textbook", "Unlimited-access theme park"),
                // 13
                new("大人になってよかったと感じる嬉しいこと",
                    "全然よくない", "大人で本当によかった",
                    "自分で歯磨きする", "好きな時間に寝られる",
                    "Good things about being an adult",
                    "Not good at all", "So glad to be an adult",
                    "Brushing your own teeth", "Sleep whenever you want"),
                // 14
                new("雨の日に気分が上がるもの・こと",
                    "気分が下がる", "最高に上がる",
                    "濡れた靴のまま歩く", "カフェでゆっくり読書",
                    "Things that lift your mood on a rainy day",
                    "Makes mood worse", "Best mood ever",
                    "Walking with soaked shoes", "Reading slowly at a café"),
                // 15
                new("運動会で盛り上がる競技",
                    "全然盛り上がらない", "最高に盛り上がる",
                    "正座の耐久レース", "全学年参加の騎馬戦",
                    "Sports-day events that get everyone excited",
                    "Dead silent", "Crowd goes wild",
                    "Endurance sitting contest", "All-grade cavalry battle"),
                // 16
                new("もらって嬉しいサプライズ",
                    "全然嬉しくない", "号泣するほど嬉しい",
                    "飴が1粒だけ", "旅行チケットのプレゼント",
                    "Surprises you'd be happy to receive",
                    "Not happy at all", "Cry with joy",
                    "A single candy", "A surprise travel ticket"),
                // 17
                new("ペットにするとかわいいいきもの",
                    "全然かわいくない", "最高にかわいい",
                    "ミミズ", "柴犬の子犬",
                    "Creatures that would be cute as pets",
                    "Not cute at all", "Absolutely adorable",
                    "An earthworm", "A Shiba Inu puppy"),
                // 18
                new("老後に楽しめそうなもの・こと",
                    "全然楽しめない", "毎日やりたい",
                    "確定申告の見直し", "夫婦で世界一周クルーズ",
                    "Things you could enjoy in retirement",
                    "Not enjoyable", "Want to do it every day",
                    "Reviewing tax returns", "A round-the-world cruise with your partner"),
                // 19
                new("引っ越し先として住みやすそうな場所",
                    "全然住みたくない", "すぐ引っ越したい",
                    "線路沿いの1Kの部屋", "海が見える一軒家",
                    "Places that seem easy and pleasant to live in",
                    "Would never live there", "Moving in right now",
                    "A tiny room next to a train line", "A house with an ocean view"),
                // 20
                new("記念日に食べたいごちそう",
                    "全然食べたくない", "最高においしい",
                    "コンビニのおにぎり", "ミシュランの星付きレストラン",
                    "Dishes you'd want for a special occasion",
                    "Not appetizing at all", "Best meal ever",
                    "A convenience-store rice ball", "A Michelin-starred restaurant"),
                // 21
                new("試験勉強がはかどるもの・環境",
                    "全然はかどらない", "10倍速で覚えられる",
                    "爆音のカフェ", "防音の個室自習室",
                    "Environments or things that help you study",
                    "Zero focus", "Memorize 10x faster",
                    "A loud café", "A soundproof private study room"),
                // 22
                new("プレゼントとして贈りやすいもの",
                    "絶対贈れない", "誰でも喜ぶ",
                    "使いかけの消しゴム", "百貨店の商品券",
                    "Things easy to give as a gift",
                    "Can never give this", "Everyone loves it",
                    "A half-used eraser", "A department store gift card"),
                // 23
                new("子どもに読み聞かせたい絵本のテーマ",
                    "絶対読まない", "毎晩読みたい",
                    "消費税の仕組み", "宝探しの大冒険",
                    "Themes for picture books to read to children",
                    "Would never read", "Read it every night",
                    "How consumption tax works", "A big treasure hunt adventure"),
                // 24
                new("長い列に並んで待ってでも食べたい食べ物",
                    "並ぶ気ゼロ", "3時間並んでも食べたい",
                    "白湯", "行列必至のラーメン",
                    "Food worth waiting in a long line for",
                    "Not worth any wait", "Worth a 3-hour wait",
                    "Boiled water", "Ramen with a legendary line"),
                // 25
                new("雨の日の楽しい過ごし方",
                    "全然楽しくない", "最高に楽しい",
                    "傘なしで外出する", "映画館でハシゴ鑑賞",
                    "Fun ways to spend a rainy day",
                    "Not fun at all", "Best day ever",
                    "Go outside without an umbrella", "Watch movies back-to-back at the cinema"),
                // 26
                new("デートで行きたい場所",
                    "絶対行きたくない", "今すぐ行きたい",
                    "区役所の待合室", "夜景の見えるレストラン",
                    "Places you'd want to go on a date",
                    "Never going there on a date", "Going right now",
                    "The waiting room at city hall", "A restaurant with a night view"),
                // 27
                new("家にあったら便利なもの",
                    "全然便利じゃない", "生活が激変する",
                    "積み上がった古雑誌", "食洗機",
                    "Things that would be convenient to have at home",
                    "Not convenient at all", "Changes your life",
                    "A pile of old magazines", "A dishwasher"),
                // 28
                new("夜ご飯に食べたいもの",
                    "食欲ゼロ", "最高においしい",
                    "賞味期限切れクラッカー", "鉄板焼きのコース料理",
                    "Things you want to eat for dinner",
                    "Zero appetite", "Absolutely delicious",
                    "Expired crackers", "A teppanyaki full-course meal"),
                // 29
                new("子どもに習わせたいスキル・習い事",
                    "全然習わせたくない", "絶対習わせたい",
                    "ハンコの押し方", "英会話",
                    "Skills or lessons you'd want your child to learn",
                    "Would never teach this", "Must learn this",
                    "How to use a personal seal", "English conversation"),
                // 30
                new("ストレス解消になるもの・こと",
                    "全然解消されない", "スッキリ消える",
                    "深呼吸を1回する", "サウナ＆水風呂",
                    "Things that relieve stress",
                    "No relief at all", "Stress gone instantly",
                    "Just one deep breath", "Sauna followed by cold bath"),
                // 31
                new("キャンプで役立つもの",
                    "全く役立たない", "なければ困る",
                    "革靴とスーツ", "多機能アーミーナイフ",
                    "Things useful for camping",
                    "Completely useless", "Can't camp without it",
                    "Dress shoes and a suit", "A multi-tool Swiss army knife"),
                // 32
                new("体調不良のときに食べやすいもの",
                    "絶対食べられない", "すぐ元気になる",
                    "激辛カレー", "消化のいいおかゆ",
                    "Things easy to eat when you're feeling sick",
                    "Impossible to eat", "Recover quickly",
                    "Extra-spicy curry", "Easy-to-digest rice porridge"),
                // 33
                new("100円で買える嬉しいもの",
                    "全然嬉しくない", "信じられないほど嬉しい",
                    "使い古した輪ゴム", "当たり付きのアイス",
                    "Things you'd be happy to buy for 100 yen",
                    "Not happy at all", "Unbelievably happy",
                    "A worn-out rubber band", "An ice cream bar with a winning stick"),
                // 34
                new("働くモチベーションが上がるもの・こと",
                    "全然上がらない", "喜んで残業できる",
                    "追加残業の通知", "ボーナス2倍の知らせ",
                    "Things that boost your motivation to work",
                    "No motivation boost", "Could work all night",
                    "Notification of extra overtime", "News that your bonus is doubled"),
                // 35
                new("部屋に飾りたいもの",
                    "絶対飾りたくない", "部屋が映える",
                    "空のダンボール箱", "本物の観葉植物",
                    "Things you'd want to decorate your room with",
                    "Would never display this", "Makes the room look great",
                    "Empty cardboard boxes", "Real indoor plants"),
                // 36
                new("眠れない夜に役立つもの・こと",
                    "余計に目が冴える", "すぐ眠くなる",
                    "エナジードリンク", "アロマの入浴剤でお風呂",
                    "Things that help when you can't sleep",
                    "Makes you more awake", "Gets you sleepy fast",
                    "An energy drink", "A bath with aromatherapy bath salts"),
                // 37
                new("子どもに人気の遊び",
                    "全然人気ない", "みんなが集まる",
                    "お勉強ドリル", "みんなで鬼ごっこ",
                    "Games and activities popular with kids",
                    "Kids ignore it", "All the kids gather around",
                    "Study drills", "Everyone playing tag together"),
                // 38
                new("老後にやってみたいこと",
                    "全然やりたくない", "絶対やりたい",
                    "部屋の窓拭き", "ヨーロッパ一人旅",
                    "Things you'd want to try in retirement",
                    "Never want to do", "Absolutely must do",
                    "Wiping the windows at home", "A solo trip around Europe"),
                // 39
                new("コンビニで買える嬉しいもの",
                    "全然嬉しくない", "最高に嬉しい",
                    "レジ袋だけ", "当たりが出たスクラッチ",
                    "Things you'd be happy to buy at a convenience store",
                    "Not happy at all", "Best feeling ever",
                    "Just a plastic bag", "A winning scratch card"),
                // 40
                new("長距離ドライブのお供になるもの",
                    "全然盛り上がらない", "最高のドライブになる",
                    "完全な無音", "好きな曲のプレイリスト",
                    "Things that make a long road trip better",
                    "No help at all", "Best drive ever",
                    "Complete silence", "A playlist of your favorite songs"),
                // 41
                new("お花見で盛り上がるもの・こと",
                    "全然盛り上がらない", "最高に盛り上がる",
                    "お弁当なしで正座", "豪華なお花見弁当",
                    "Things that make cherry blossom viewing exciting",
                    "No excitement at all", "Best party ever",
                    "Sitting with no food", "A gorgeous bento for hanami"),
                // 42
                new("一人で楽しめるもの・こと",
                    "全然楽しめない", "永遠にできる",
                    "天井を見つめる", "好きな映画を一気見",
                    "Things you can enjoy alone",
                    "Not enjoyable solo", "Could do it forever",
                    "Staring at the ceiling", "Binge-watching your favorite films"),
                // 43
                new("子どもの誕生日パーティーで喜ばれるもの",
                    "全然喜ばれない", "大興奮で喜ぶ",
                    "鉛筆1本だけ", "遊園地の年間パスポート",
                    "Things kids would love at a birthday party",
                    "Kids are disappointed", "Kids go absolutely wild",
                    "A single pencil", "An annual pass to an amusement park"),
                // 44
                new("海外旅行で買いたいお土産",
                    "絶対買いたくない", "絶対買って帰りたい",
                    "現地のレシート", "限定のブランドアイテム",
                    "Souvenirs you'd want to buy on a trip abroad",
                    "Would never buy", "Must bring home",
                    "A local receipt", "A limited-edition brand item"),
                // 45
                new("運動不足解消になるもの・こと",
                    "全然解消されない", "体が変わる",
                    "ベッドで寝返りを打つ", "パーソナルジムに通う",
                    "Things that help fix lack of exercise",
                    "No effect at all", "Body transforms",
                    "Rolling over in bed", "Going to a personal training gym"),
                // 46
                new("二人で食べると美味しいもの",
                    "一人で食べた方がいい", "二人で食べると倍旨い",
                    "飴1粒を半分こ", "鍋料理",
                    "Food that tastes better when shared with someone",
                    "Better to eat alone", "Twice as delicious together",
                    "Splitting one candy in half", "Hot pot"),
                // 47
                new("家族で楽しめるもの・こと",
                    "家族でやりたくない", "家族の絆が深まる",
                    "確定申告の話し合い", "みんなでボードゲーム",
                    "Things the whole family can enjoy together",
                    "Family would never do this", "Deepens family bonds",
                    "Discussing tax returns together", "Playing board games as a family"),
                // 48
                new("友達と盛り上がれるゲーム",
                    "全然盛り上がらない", "夜通しできる",
                    "足し算クイズ大会", "大人数での人狼ゲーム",
                    "Games that get exciting with friends",
                    "No excitement", "Could play all night",
                    "Addition quiz competition", "A large group game of Werewolf"),
                // 49
                new("夏祭りで楽しいもの",
                    "全然楽しくない", "最高に楽しい",
                    "ゴミ袋を持つ係", "屋台を食べ歩き",
                    "Fun things at a summer festival",
                    "Not fun at all", "Best night ever",
                    "Being in charge of the trash bag", "Eating your way through the food stalls"),
                // 50
                new("寝る前にすると眠れるもの・こと",
                    "余計に眠れなくなる", "3分で熟睡できる",
                    "エナジードリンクを飲む", "軽いストレッチをする",
                    "Things that help you fall asleep before bed",
                    "Makes you more awake", "Asleep within 3 minutes",
                    "Drinking an energy drink", "Doing some light stretching"),
                // 51
                new("二日酔いのときに食べやすいもの",
                    "絶対食べられない", "すぐ回復する",
                    "揚げたての焼肉", "しじみのお味噌汁",
                    "Food easy to eat when hungover",
                    "Impossible to eat", "Recover quickly",
                    "Fresh-fried yakiniku", "Clam miso soup"),
                // 52
                new("子どもが喜ぶおやつ",
                    "全然喜ばない", "大喜びする",
                    "にがりせんべい", "好きなケーキを選び放題",
                    "Snacks that kids love",
                    "Kids hate it", "Kids are overjoyed",
                    "Bitter mineral crackers", "Choose any cake you want"),
                // 53
                new("忙しいときに助かるもの・サービス",
                    "余計に忙しくなる", "時間が生まれる",
                    "追加タスクの連絡", "宅配クリーニングサービス",
                    "Things or services that help when you're busy",
                    "Makes you more busy", "Creates extra time",
                    "Notification of more tasks", "Home pickup dry cleaning service"),
                // 54
                new("冬に食べたい温かいもの",
                    "全然温まらない", "体の芯まで温まる",
                    "冷たい水だけ", "本格的なすき焼き",
                    "Warm foods you want to eat in winter",
                    "No warmth at all", "Warm to the core",
                    "Just cold water", "Authentic sukiyaki hot pot"),
                // 55
                new("日曜の朝に楽しいもの・こと",
                    "全然楽しくない", "最高に幸せ",
                    "早朝に届く請求書", "好きな朝ごはんを外食",
                    "Enjoyable things on a Sunday morning",
                    "Not enjoyable at all", "Pure bliss",
                    "An invoice that arrives at dawn", "Eating your favorite breakfast out"),
                // 56
                new("初対面の人と仲良くなれるもの・こと",
                    "むしろ距離が開く", "一瞬で打ち解ける",
                    "無言でじっと見つめる", "共通の趣味を見つける",
                    "Things that help you bond with someone you just met",
                    "Pushes people further away", "Instant best friends",
                    "Staring at them in silence", "Discovering a shared hobby"),
                // 57
                new("困ったときに頼りになる人の特徴",
                    "全然頼りにならない", "完璧に助けてくれる",
                    "「知らん」と言う人", "すぐ動いてくれる人",
                    "Traits of a reliable person when you're in trouble",
                    "Not reliable at all", "Solves everything for you",
                    "Someone who says 'Not my problem'", "Someone who acts immediately"),
                // 58
                new("ハイキングに持っていくと役立つもの",
                    "全く役立たない", "これで安心",
                    "革靴とスーツ", "軽量の登山靴",
                    "Things useful to bring on a hike",
                    "Completely useless", "Feel fully prepared",
                    "Leather shoes and a suit", "Lightweight hiking boots"),
                // 59
                new("記憶に残る嬉しい体験",
                    "すぐ忘れる", "一生忘れない",
                    "コンビニのポイント付与", "初めての海外一人旅",
                    "Happy experiences that stay in your memory",
                    "Forget immediately", "Remember for life",
                    "Earning convenience store points", "Your first solo trip abroad"),
                // 60
                new("料理が得意な人が作ってくれると嬉しいもの",
                    "全然嬉しくない", "感動して泣く",
                    "ぬるいお湯だけ", "本格フルコース料理",
                    "Dishes you'd love a good cook to make for you",
                    "Not happy at all", "Moved to tears",
                    "Lukewarm water", "A full authentic multi-course meal"),
                // 61
                new("気分転換になるもの・こと",
                    "全然気分転換にならない", "完全にリフレッシュ",
                    "同じ部屋で深呼吸", "日帰り温泉旅行",
                    "Things that help you change your mood",
                    "No change at all", "Completely refreshed",
                    "Deep breathing in the same room", "A day trip to a hot spring"),
                // 62
                new("道に迷ったときに助かるもの",
                    "全然助からない", "すぐ解決する",
                    "白紙の地図", "地元の人に声をかける",
                    "Things that help when you're lost",
                    "No help at all", "Solved right away",
                    "A blank map", "Asking a local for directions"),
                // 63
                new("子どもが夢中になれるもの",
                    "全然夢中にならない", "時間を忘れる",
                    "計算ドリルの宿題", "本物の昆虫採集セット",
                    "Things kids get completely absorbed in",
                    "Kids ignore it", "Kids lose track of time",
                    "Math drill homework", "A real bug-catching kit"),
                // 64
                new("プロポーズで感動できるもの・こと",
                    "むしろ引いてしまう", "一生の宝物になる",
                    "スーパーのレシートを渡す", "思い出の場所でサプライズ",
                    "Proposal gestures that are truly moving",
                    "Creepy or off-putting", "A memory to treasure for life",
                    "Handing them a supermarket receipt", "A surprise at a meaningful place"),
                // 65
                new("老人ホームで楽しめるもの・こと",
                    "全然楽しめない", "毎日やりたい",
                    "確定申告書の整理", "みんなでカラオケ大会",
                    "Things elderly people can enjoy at a care home",
                    "Not enjoyable at all", "Want to do it every day",
                    "Sorting through old tax returns", "Karaoke party with everyone"),
                // 66
                new("二人でいると楽しい時間",
                    "一人の方がいい", "ずっとこのままでいたい",
                    "お互い無言でスマホ", "一緒に料理を作る時間",
                    "Time that's fun when spent with someone",
                    "Better alone", "Want it to last forever",
                    "Both silently on their phones", "Cooking together"),
                // 67
                new("コスパが良くて嬉しいもの・サービス",
                    "完全に損をする", "信じられないお得",
                    "翌日に壊れる安い傘", "年会費無料の空港ラウンジ",
                    "Things or services with great value for money",
                    "Total waste of money", "Unbelievable bargain",
                    "A cheap umbrella that breaks the next day", "A free-membership airport lounge"),
                // 68
                new("子どもに残してあげたいもの",
                    "全然残したくない", "最高の贈り物",
                    "古い雑誌の山", "自分の体験談を書いたノート",
                    "Things you'd want to leave behind for your children",
                    "Would never leave this", "The greatest gift",
                    "A pile of old magazines", "A notebook full of your life stories"),
                // 69
                new("外食で頼みたいもの",
                    "絶対頼みたくない", "毎回頼む",
                    "白湯だけ", "看板メニューのコース",
                    "Dishes you'd want to order at a restaurant",
                    "Would never order", "Order it every single time",
                    "Just hot water", "The signature full-course menu"),
                // 70
                new("春に楽しめるもの・こと",
                    "全然楽しめない", "最高の季節",
                    "花粉症の薬を飲む", "お花見でバーベキュー",
                    "Things you can enjoy in spring",
                    "Not enjoyable", "Best season of the year",
                    "Taking hay fever medicine", "BBQ under the cherry blossoms"),
                // 71
                new("インドア派が楽しめるもの・こと",
                    "全然楽しめない", "永遠にいられる",
                    "天井の染みを数える", "好きな映画を一気見",
                    "Things indoor people can enjoy",
                    "Not enjoyable indoors", "Could stay inside forever",
                    "Counting stains on the ceiling", "Binge-watching favorite movies"),
                // 72
                new("アウトドア派が楽しめるもの・こと",
                    "全然楽しめない", "一日中いられる",
                    "ソファでゴロゴロ", "山登りで絶景を眺める",
                    "Things outdoor lovers can enjoy",
                    "Not enjoyable outside", "Could stay out all day",
                    "Lounging on the sofa", "Hiking to see a breathtaking view"),
                // 73
                new("仕事終わりに嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "追加の残業が入る", "同僚と楽しい飲み会",
                    "Things you're happy about after finishing work",
                    "Not happy at all", "Absolute bliss",
                    "Getting assigned extra overtime", "A fun dinner out with coworkers"),
                // 74
                new("寒い日に外出したくなるもの・こと",
                    "絶対外出したくない", "すぐ飛び出す",
                    "税務署からの呼び出し", "駅前のイルミネーション",
                    "Things that make you want to go outside on a cold day",
                    "Would never go out", "Rush outside instantly",
                    "A summons from the tax office", "Illuminations in front of the station"),
                // 75
                new("停電の夜に楽しめること",
                    "全然楽しくない", "最高に楽しい",
                    "暗闇でじっと正座", "キャンドルを囲んで話す",
                    "Things you can enjoy during a blackout at night",
                    "Not fun at all", "Best night of the year",
                    "Sitting still in pitch darkness", "Gathering around candles and talking"),
                // 76
                new("カラオケで盛り上がれるもの・こと",
                    "全然盛り上がらない", "大合唱になる",
                    "無音でただ立ってる", "全員が知ってる曲で合唱",
                    "Things that make karaoke exciting",
                    "Total silence", "Everyone sings along",
                    "Standing there in silence", "Singing a song everyone knows"),
                // 77
                new("誕生日パーティーで盛り上がる出し物",
                    "場が凍りつく", "爆発的に盛り上がる",
                    "領収書の読み上げ", "みんなでダンスバトル",
                    "Performances that hype up a birthday party",
                    "Kills the vibe completely", "Crowd goes wild",
                    "Reading receipts aloud", "A dance battle with everyone"),
                // 78
                new("家の中でできる楽しいこと",
                    "全然楽しくない", "ずっとできる",
                    "壁の汚れを数える", "料理を作って食べる",
                    "Fun things you can do inside the house",
                    "Not fun at all", "Could do it forever",
                    "Counting scuff marks on the wall", "Cooking and eating a meal"),
                // 79
                new("風邪をひいたときに助かるもの",
                    "全然助からない", "すぐに楽になる",
                    "生のニンニクをかじる", "葛根湯と温かい鍋",
                    "Things that help when you have a cold",
                    "No help at all", "Feel better quickly",
                    "Biting into raw garlic", "Herbal medicine and hot pot"),
                // 80
                new("勉強のやる気が出るもの・こと",
                    "やる気ゼロになる", "集中が続く",
                    "追加の宿題プリント", "好きな音楽をかけながら",
                    "Things that motivate you to study",
                    "Kills all motivation", "Stay focused",
                    "Extra homework printouts", "Listening to your favorite music"),
                // 81
                new("友達と過ごす休日に楽しいこと",
                    "全然楽しくない", "最高の一日",
                    "お互い黙ってスマホ", "日帰りで小旅行",
                    "Fun things to do with friends on a day off",
                    "Not fun at all", "Best day ever",
                    "Both silently scrolling their phones", "A spontaneous day trip"),
                // 82
                new("学校や会社に行くのが楽しみになる嬉しいこと",
                    "全然楽しみじゃない", "飛び起きる",
                    "怒られる予定がある", "仲のいい友達と話せる",
                    "Things that make you excited to go to school or work",
                    "Dread going", "Jump out of bed",
                    "Knowing you'll get scolded", "Getting to chat with a close friend"),
                // 83
                new("旅行の思い出として嬉しいもの",
                    "全然嬉しくない", "一生の宝物",
                    "コンビニのレシートだけ", "現地の人との写真",
                    "Things you'd be happy to have as travel memories",
                    "Not happy at all", "Treasure it for life",
                    "Just a convenience store receipt", "A photo with a local you met"),
                // 84
                new("年末年始に楽しめるもの・こと",
                    "全然楽しくない", "最高に楽しい",
                    "確定申告の下準備", "家族みんなでお雑煮",
                    "Things you can enjoy over New Year",
                    "Not enjoyable at all", "Best time of year",
                    "Preparing documents for tax season", "Ozoni with the whole family"),
                // 85
                new("一人旅で嬉しいもの・こと",
                    "全然嬉しくない", "最高の体験",
                    "乗り継ぎを失敗する", "旅先での素敵な出会い",
                    "Happy things about traveling alone",
                    "Not happy at all", "Life-changing experience",
                    "Missing your connecting flight", "A wonderful encounter at your destination"),
                // 86
                new("運動会のお昼ご飯として嬉しいもの",
                    "全然嬉しくない", "最高においしい",
                    "水だけ", "親の手作りお弁当",
                    "Happy lunches at a school sports day",
                    "Not happy at all", "Absolutely delicious",
                    "Just water", "A homemade bento from your parents"),
                // 87
                new("暇つぶしになるもの・こと",
                    "全然暇つぶしにならない", "時間を忘れる",
                    "天井の染みを数える", "ハマった漫画を一気読み",
                    "Things that help pass the time",
                    "No help at all", "Lose all track of time",
                    "Counting ceiling stains", "Binge-reading a manga you love"),
                // 88
                new("引っ越しのとき助かるもの・こと",
                    "全然助からない", "あっという間に終わる",
                    "段ボール箱が1枚だけ", "引っ越し業者のフルパック",
                    "Things that help when moving to a new place",
                    "No help at all", "Done in no time",
                    "Having only one cardboard box", "Full-service movers"),
                // 89
                new("子育てで楽しい瞬間",
                    "全然楽しくない", "最高に幸せ",
                    "深夜のおむつ替え", "初めて「ママ」と言った日",
                    "Joyful moments in raising a child",
                    "Not enjoyable at all", "Greatest happiness",
                    "Midnight diaper changes", "The day they first said 'Mama'"),
                // 90
                new("悲しいときに元気が出るもの・こと",
                    "むしろ落ち込む", "すぐ元気になる",
                    "さらに悲しいニュース", "友達に電話して話す",
                    "Things that cheer you up when you're sad",
                    "Makes you feel worse", "Cheers you up instantly",
                    "Even sadder news", "Calling a friend to talk"),
                // 91
                new("仕事で達成感があるもの・こと",
                    "全然達成感ない", "最高の達成感",
                    "消耗品の在庫補充", "大きなプロジェクトを完了",
                    "Work tasks that give a sense of accomplishment",
                    "No satisfaction at all", "Greatest satisfaction ever",
                    "Restocking office supplies", "Completing a major project"),
                // 92
                new("記念日のサプライズとして嬉しいもの",
                    "全然嬉しくない", "号泣するほど嬉しい",
                    "割り箸1膳だけ", "好きなお店でのサプライズ食事",
                    "Surprises you'd love to receive on an anniversary",
                    "Not happy at all", "Cry with joy",
                    "A single pair of disposable chopsticks", "A surprise dinner at your favorite restaurant"),
                // 93
                new("二日酔いのときに助かるもの",
                    "余計につらくなる", "すぐ回復する",
                    "追加のお酒を飲む", "スポドリと二度寝",
                    "Things that help when you're hungover",
                    "Makes it much worse", "Recover quickly",
                    "Drinking more alcohol", "Sports drink and going back to sleep"),
                // 94
                new("秋に楽しめるもの・こと",
                    "全然楽しくない", "最高の季節",
                    "落ち葉の掃き掃除", "紅葉スポットへのドライブ",
                    "Things you can enjoy in autumn",
                    "Not enjoyable at all", "Best season of the year",
                    "Sweeping up fallen leaves", "A drive to see autumn foliage"),
                // 95
                new("お風呂上がりに嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "濡れたタオルしかない", "ふかふかのバスローブ",
                    "Happy things after getting out of the bath",
                    "Not happy at all", "Absolute bliss",
                    "Only a wet towel available", "A fluffy bathrobe waiting for you"),
                // 96
                new("寝坊した朝に助かるもの・こと",
                    "全然助からない", "間に合ってしまう",
                    "ひどい渋滞情報", "その日がテレワークだった",
                    "Things that help when you've overslept",
                    "No help at all", "Somehow still make it",
                    "News of terrible traffic jams", "Finding out it's a work-from-home day"),
                // 97
                new("お正月に嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "年明けの税金通知書", "親戚からのお年玉",
                    "Happy things about New Year",
                    "Not happy at all", "Pure happiness",
                    "A tax notice right after New Year", "New Year's money from relatives"),
                // 98
                new("冬のデートで楽しいもの・場所",
                    "全然楽しくない", "一生の思い出",
                    "駅前で立ち話するだけ", "夜景のイルミネーション",
                    "Fun things or places for a winter date",
                    "Not fun at all", "A memory for life",
                    "Just chatting in front of the station", "An illumination show with night views"),
                // 99
                new("大切な人への気持ちを伝えるもの・方法",
                    "全然伝わらない", "完璧に伝わる",
                    "スーパーのレシートを渡す", "手書きの手紙",
                    "Ways to express your feelings to someone special",
                    "Feeling not conveyed at all", "Perfectly understood",
                    "Handing them a supermarket receipt", "A handwritten letter"),
                // 100
                new("人生を振り返って一番嬉しかった体験",
                    "全く嬉しくなかった", "最高に嬉しかった",
                    "財布に小銭を見つけた", "子どもの成長を見守った日々",
                    "The happiest experience when you look back on life",
                    "Not happy at all", "The greatest joy in life",
                    "Finding loose change in your wallet", "Watching your child grow up"),
            };
        }
    }
}
