using System.Collections.Generic;
using UnityEngine;

namespace BomBomLemon.Game.Topics
{
    [CreateAssetMenu(fileName = "TopicDatabase", menuName = "BomBom Lemon/Topic Database", order = 1)]
    public class TopicDatabase : ScriptableObject
    {
        [SerializeField] private List<Topic> topics = new();

        public IReadOnlyList<Topic> Topics => topics;

        public Topic GetRandom()
        {
            if (topics.Count == 0) return FallbackTopic();
            return topics[Random.Range(0, topics.Count)];
        }

        static Topic FallbackTopic() => new(
            "好きな食べ物の甘さ", "甘くない", "めちゃ甘い", "塩昆布", "砂糖まみれのスイーツ",
            "Sweetness of your fav food", "Not sweet", "Extremely sweet", "Salted kelp", "Sugar-coated everything"
        );

        [ContextMenu("Load Default Japanese Topics")]
        public void LoadDefaultTopics()
        {
            topics = new List<Topic>
            {
                // 1
                new("誕生日にもらって嬉しいもの",
                    "全く嬉しくない", "最高に嬉しい",
                    "動物の死骸", "家と高級車のカギ一式",
                    "Things you're happy to receive for your birthday",
                    "Horrifying", "Life-changingly amazing",
                    "The carcass of an animal", "Keys to a house and a luxury car"),
                // 2
                new("空腹のときに食べたいもの",
                    "食欲ゼロ", "最高においしい",
                    "土をこねた泥団子", "世界最高シェフの晩餐",
                    "Things you want to eat when starving",
                    "Zero appetite", "Absolutely transcendent",
                    "A mud dumpling kneaded from dirt", "Dinner prepared by the world's greatest chef"),
                // 3
                new("夏に涼しくなれるもの・こと",
                    "全然涼しくない", "極限まで涼しい",
                    "熱々の鍋料理", "南極の氷河でゴロ寝",
                    "Things that cool you down in summer",
                    "Makes you even hotter", "Perfectly chilled",
                    "A steaming hot pot meal", "Napping on a glacier in Antarctica"),
                // 4
                new("子どものころに欲しかったもの",
                    "全然欲しくなかった", "死ぬほど欲しかった",
                    "親からのビンタ", "自分専用の秘密基地",
                    "Things you wanted as a child",
                    "Nightmare gift", "Desperately wanted",
                    "A slap in the face from a parent", "Your very own private secret base"),
                // 5
                new("旅行先として行きたい場所",
                    "絶対行きたくない", "今すぐ行きたい",
                    "肥溜めの見学ツアー", "誰もいない秘境の楽園",
                    "Places you want to visit as a travel destination",
                    "Never want to go", "Want to go right now",
                    "A guided tour of a rural cesspit", "A paradise in the wilderness nobody has found"),
                // 6
                new("疲れたときに癒されるもの・こと",
                    "全然癒されない", "完全に癒される",
                    "上司からの追加指示", "無人島の個人リゾート",
                    "Things that heal you when you're exhausted",
                    "Makes exhaustion worse", "Fully restored",
                    "More instructions from your boss", "A private resort on a deserted island"),
                // 7
                new("朝起きるのが楽しみになるもの",
                    "全然楽しみじゃない", "飛び起きる",
                    "近所の工事の爆音", "給料3倍の辞令の朝",
                    "Things that make you excited to wake up",
                    "Dread waking up", "Jump out of bed",
                    "Deafening construction noise right next door", "Morning an order arrives tripling your salary"),
                // 8
                new("無人島に持っていったら役立つもの",
                    "全く役に立たない", "命が救われる",
                    "スマホの充電器だけ", "全自動サバイバルAI",
                    "Things useful to bring to a deserted island",
                    "Completely useless", "Life-saving",
                    "Just a phone charger (no power source)", "A fully automatic survival AI"),
                // 9
                new("友達に紹介したいもの・こと",
                    "紹介したくない", "絶対紹介したい",
                    "悪臭を放つ近所の川", "運命が変わる秘密の場所",
                    "Things you want to recommend to friends",
                    "Would never recommend", "Must share with everyone",
                    "The foul-smelling river nearby", "A secret place that changes your destiny"),
                // 10
                new("寒い冬に温まれるもの・こと",
                    "全然温まらない", "芯まで温まる",
                    "氷のシャワーを浴びる", "火山の隣の露天風呂",
                    "Things that warm you up in cold winter",
                    "Makes you even colder", "Warm to the core",
                    "A shower of ice water", "An open-air bath right next to a volcano"),
                // 11
                new("お腹が痛いときに助かるもの",
                    "全然助からない", "一瞬で治る",
                    "激辛唐辛子をそのまま", "飲んだら5秒で治る薬茶",
                    "Things that help when you have a stomachache",
                    "Makes it much worse", "Heals in an instant",
                    "Raw extra-spicy chili peppers straight up", "An herbal tea that cures you in 5 seconds"),
                // 12
                new("子どもに人気がありそうなもの",
                    "子どもが逃げ出す", "取り合いになる",
                    "漢字ドリル100枚追加", "空を自由に飛べる道具",
                    "Things that seem popular with kids",
                    "Kids run away from it", "Kids fight over it",
                    "100 extra kanji drill sheets", "A device that lets you fly freely in the sky"),
                // 13
                new("大人になってよかったと感じる嬉しいこと",
                    "全然よくない", "大人で本当によかった",
                    "毎月届く光熱費の請求書", "誰にも門限を言われない",
                    "Good things about being an adult",
                    "Not good at all", "So glad to be an adult",
                    "Monthly utility bills arriving in the mailbox", "Nobody ever tells you when to come home"),
                // 14
                new("雨の日に気分が上がるもの・こと",
                    "気分が最悪になる", "最高に上がる",
                    "雨漏りで部屋が水浸し", "嵐の特等席で読む小説",
                    "Things that lift your mood on a rainy day",
                    "Makes mood awful", "Best mood ever",
                    "Rain leaking through the roof and flooding your room", "Reading a novel in a front-row seat watching a storm"),
                // 15
                new("運動会で盛り上がる競技",
                    "全員が寝そうになる", "最高に盛り上がる",
                    "全員で正座する耐久戦", "空飛ぶリレー競走",
                    "Sports-day events that get everyone excited",
                    "Everyone nearly falls asleep", "Crowd goes absolutely wild",
                    "An endurance contest of sitting in seiza", "A relay race where everyone flies through the air"),
                // 16
                new("もらって嬉しいサプライズ",
                    "全然嬉しくない", "号泣するほど嬉しい",
                    "使用済みの絆創膏", "白紙小切手のプレゼント",
                    "Surprises you'd be happy to receive",
                    "Not happy at all", "Cry with joy",
                    "A used bandage", "A blank cheque as a gift"),
                // 17
                new("ペットにするとかわいいいきもの",
                    "全然かわいくない", "最高にかわいい",
                    "近所のドブネズミ", "手乗りサイズのシャチ",
                    "Creatures that would be cute as pets",
                    "Absolutely not cute", "Impossibly adorable",
                    "A sewer rat from the neighborhood", "A palm-sized killer whale"),
                // 18
                new("老後に楽しめそうなもの・こと",
                    "全然楽しめない", "毎日やりたい",
                    "テレビを眺めるだけの一日", "月に別荘を持って住む",
                    "Things you could enjoy in retirement",
                    "Not enjoyable at all", "Want to do it every single day",
                    "A whole day spent doing nothing but staring at the TV", "Living in your own villa on the moon"),
                // 19
                new("引っ越し先として住みやすそうな場所",
                    "絶対住みたくない", "今すぐ引っ越したい",
                    "活火山の火口付近", "崖の上のガラス張りの家",
                    "Places that seem easy and pleasant to live in",
                    "Would never live there", "Moving in right now",
                    "Right next to the crater of an active volcano", "A glass house perched on the edge of a cliff"),
                // 20
                new("記念日に食べたいごちそう",
                    "全然食べたくない", "最高においしい",
                    "10年前の缶詰カレー", "伝説の職人の特製寿司",
                    "Dishes you'd want for a special occasion",
                    "Completely unappetizing", "Best meal in existence",
                    "A 10-year-old can of curry", "Hand-crafted sushi by a legendary master"),
                // 21
                new("試験勉強がはかどるもの・環境",
                    "全然はかどらない", "10倍速で覚えられる",
                    "爆音パチンコ店の真隣", "記憶が10倍になる椅子",
                    "Environments or things that help you study",
                    "Zero focus possible", "Memorize 10x faster",
                    "Right next to a blaring pachinko parlor", "A chair that multiplies your memory 10x"),
                // 22
                new("プレゼントとして贈りやすいもの",
                    "絶対贈れない", "誰でも喜ぶ",
                    "使用済みの歯ブラシ", "その人の名前入りの星",
                    "Things easy to give as a gift",
                    "Can never give this", "Everyone loves it",
                    "A used toothbrush", "A star officially named after them"),
                // 23
                new("子どもに読み聞かせたい絵本のテーマ",
                    "絶対読まない", "毎晩読みたい",
                    "住民税の計算方法", "魔法の力で世界を救う話",
                    "Themes for picture books to read to children",
                    "Would never read", "Read it every night",
                    "How to calculate residential tax", "Saving the world with magical powers"),
                // 24
                new("長い列に並んで待ってでも食べたい食べ物",
                    "並ぶ気ゼロ", "3時間並んでも食べたい",
                    "水をかけただけのご飯", "幻の職人の特製ラーメン",
                    "Food worth waiting in a long line for",
                    "Not worth a second of waiting", "Worth a 3-hour wait",
                    "Plain rice with just water poured over it", "Ramen by a phantom legendary master"),
                // 25
                new("雨の日の楽しい過ごし方",
                    "全然楽しくない", "最高に楽しい",
                    "全身びしょ濡れで通勤", "特等席で嵐を鑑賞する",
                    "Fun ways to spend a rainy day",
                    "Not fun at all", "Best day ever",
                    "Commuting completely drenched", "Watching a raging storm from the best seat in the house"),
                // 26
                new("デートで行きたい場所",
                    "絶対行きたくない", "今すぐ行きたい",
                    "下水処理場の工場見学", "秘密の絶景スポット",
                    "Places you'd want to go on a date",
                    "Never going there on a date", "Going right now",
                    "A sewage treatment plant tour", "A secret spot with a view that takes your breath away"),
                // 27
                new("家にあったら便利なもの",
                    "むしろ邪魔になる", "生活が激変する",
                    "壊れた洗濯機が5台", "言葉を理解する掃除ロボット",
                    "Things that would be convenient to have at home",
                    "Actually gets in the way", "Life completely transforms",
                    "Five broken washing machines", "A cleaning robot that understands everything you say"),
                // 28
                new("夜ご飯に食べたいもの",
                    "食欲ゼロ", "最高においしい",
                    "腐りかけの残り物", "伝説の料亭の秘伝の鍋",
                    "Things you want to eat for dinner",
                    "Zero appetite", "Absolutely transcendent",
                    "Half-rotted leftover food", "A secret hot pot recipe from a legendary restaurant"),
                // 29
                new("子どもに習わせたいスキル・習い事",
                    "全然習わせたくない", "絶対習わせたい",
                    "ファックスの操作方法", "動物と話せる言語",
                    "Skills or lessons you'd want your child to learn",
                    "Would never teach this", "Must learn this",
                    "How to operate a fax machine", "A language for communicating with animals"),
                // 30
                new("ストレス解消になるもの・こと",
                    "むしろストレスが増す", "一瞬でゼロになる",
                    "壁に向かっての独り言", "誰もいない無人島で絶叫",
                    "Things that relieve stress",
                    "Adds more stress", "Stress vanishes in an instant",
                    "Talking to yourself facing a blank wall", "Screaming at the top of your lungs on a deserted island"),
                // 31
                new("キャンプで役立つもの",
                    "全く役立たない", "なければ死ぬ",
                    "フォーマルなドレス", "全自動調理キャンプAI",
                    "Things useful for camping",
                    "Completely useless", "Can't survive without it",
                    "A formal evening dress", "A fully automatic AI that cooks your entire camp meal"),
                // 32
                new("体調不良のときに食べやすいもの",
                    "絶対食べられない", "一瞬で元気になる",
                    "変色してカビたチーズ", "謎の薬草師の回復粥",
                    "Things easy to eat when you're feeling sick",
                    "Impossible to eat", "Recover in an instant",
                    "Discoloured cheese completely covered in mould", "Recovery porridge from a mysterious herbalist"),
                // 33
                new("100円で買える嬉しいもの",
                    "全然嬉しくない", "信じられないほど嬉しい",
                    "割れた消しゴムの欠片", "万券が当たるスクラッチ",
                    "Things you'd be happy to buy for 100 yen",
                    "Not happy at all", "Unbelievably happy",
                    "A broken fragment of an eraser", "A scratch card that wins you ten thousand yen"),
                // 34
                new("働くモチベーションが上がるもの・こと",
                    "やる気が消える", "喜んで残業できる",
                    "真夜中の緊急追加仕事", "突然の給料3倍通知",
                    "Things that boost your motivation to work",
                    "Kills all motivation", "Could work all night gladly",
                    "Emergency extra work assigned at midnight", "A sudden notification that your salary is tripled"),
                // 35
                new("部屋に飾りたいもの",
                    "絶対飾りたくない", "部屋が激変する",
                    "生ゴミが入った臭い袋", "本物の巨匠の原画1枚",
                    "Things you'd want to decorate your room with",
                    "Would never display this", "Room completely transformed",
                    "A reeking bag stuffed full of raw kitchen waste", "One original painting by a true master artist"),
                // 36
                new("眠れない夜に役立つもの・こと",
                    "余計に目が冴える", "3分で熟睡できる",
                    "深夜のエスプレッソ3杯", "聴いた瞬間眠れる謎の曲",
                    "Things that help when you can't sleep",
                    "Makes you even more awake", "Asleep within 3 minutes",
                    "Three espressos in the middle of the night", "A mysterious song that knocks you out the moment you hear it"),
                // 37
                new("子どもに人気の遊び",
                    "子どもが泣き出す", "みんなが集まる",
                    "漢字100問テスト", "夢のテーマパーク貸し切り",
                    "Games and activities popular with kids",
                    "Kids start crying", "All the kids come running",
                    "A 100-question kanji test", "An entire dream theme park reserved just for you"),
                // 38
                new("老後にやってみたいこと",
                    "全然やりたくない", "絶対やりたい",
                    "溜め込んだ書類の整理", "世界の絶景を全制覇",
                    "Things you'd want to try in retirement",
                    "Never want to do", "Absolutely must do",
                    "Sorting through years of accumulated documents", "Visiting every breathtaking view in the entire world"),
                // 39
                new("コンビニで買える嬉しいもの",
                    "全然嬉しくない", "最高に嬉しい",
                    "賞味期限切れのおにぎり", "1000万円当たりの宝くじ",
                    "Things you'd be happy to buy at a convenience store",
                    "Not happy at all", "Best feeling ever",
                    "A rice ball that's already past its expiry date", "A lottery ticket that wins ten million yen"),
                // 40
                new("長距離ドライブのお供になるもの",
                    "全然盛り上がらない", "最高のドライブになる",
                    "砂漠で電波なしの無音", "好きな人が隣にいる車内",
                    "Things that make a long road trip better",
                    "No help at all", "Best drive of your life",
                    "Total silence with no signal in the desert", "Sitting in the car with the person you like right next to you"),
                // 41
                new("お花見で盛り上がるもの・こと",
                    "全然盛り上がらない", "最高に盛り上がる",
                    "雨の中お弁当なし正座", "散る夜桜の貸切の席",
                    "Things that make cherry blossom viewing exciting",
                    "No excitement at all", "Best outdoor party ever",
                    "Sitting in the rain with no food", "A private reserved seat under falling night sakura"),
                // 42
                new("一人で楽しめるもの・こと",
                    "全然楽しめない", "永遠にできる",
                    "壁のしみを一晩数える", "大好きな漫画全巻一気読み",
                    "Things you can enjoy alone",
                    "Not enjoyable solo", "Could do it forever",
                    "Counting wall stains all night long", "Reading every single volume of your favorite manga in one go"),
                // 43
                new("子どもの誕生日パーティーで喜ばれるもの",
                    "子どもが凍りつく", "大興奮で喜ぶ",
                    "当日届いた宿題の山", "本物のマジシャンの実演",
                    "Things kids would love at a birthday party",
                    "Kids go silent in horror", "Kids go absolutely wild",
                    "A huge pile of homework delivered on the day", "A live performance by a real professional magician"),
                // 44
                new("海外旅行で買いたいお土産",
                    "絶対買いたくない", "絶対買って帰りたい",
                    "その辺の石ころ", "世界に1個だけのアクセ",
                    "Souvenirs you'd want to buy on a trip abroad",
                    "Would never buy", "Must bring home",
                    "A pebble from the side of the road", "A one-of-a-kind accessory that exists nowhere else in the world"),
                // 45
                new("運動不足解消になるもの・こと",
                    "全然解消されない", "体が完全に変わる",
                    "エレベーターで1階移動", "専属コーチが毎日来る",
                    "Things that help fix lack of exercise",
                    "No effect whatsoever", "Body completely transforms",
                    "Taking the elevator to move up or down just one floor", "A personal coach who shows up at your door every day"),
                // 46
                new("友達に自慢したくなるもの",
                    "誰にも言いたくない", "今すぐ全員に自慢したい",
                    "会社のコピー機の使い方を覚えた", "世界記録を達成した",
                    "Things you can't wait to brag to your friends about",
                    "Don't want to tell anyone", "Want to brag to literally everyone right now",
                    "Finally figured out how to use the office copier", "You just broke a world record"),
                // 47
                new("家族で楽しめるもの・こと",
                    "家族全員が嫌がる", "家族の絆が深まる",
                    "無言で食べるだけの夕食", "家族全員で行く夢の旅行",
                    "Things the whole family can enjoy together",
                    "Every family member dreads it", "Deepens family bonds",
                    "A dinner where everyone eats in complete silence", "A dream trip the whole family goes on together"),
                // 48
                new("友達と盛り上がれるゲーム",
                    "全員が無言になる", "夜通しできる",
                    "全員でひたすら沈黙する", "本物の廃墟で謎解き脱出",
                    "Games that get exciting with friends",
                    "Everyone goes completely silent", "Could play all night",
                    "Everyone sitting together in complete silence", "A real escape-room challenge inside an actual abandoned building"),
                // 49
                new("夏祭りで楽しいもの",
                    "全然楽しくない", "最高に楽しい",
                    "強制ゴミ拾い係に任命", "好きな人と見る特等席",
                    "Fun things at a summer festival",
                    "Not fun at all", "Best night of the year",
                    "Being forcibly assigned as the trash collector", "A front-row seat watching fireworks with the person you like"),
                // 50
                new("寝る前にすると眠れるもの・こと",
                    "余計に眠れなくなる", "3分で熟睡できる",
                    "就寝前の恐怖映画3本立て", "雲みたいなふわふわの布団",
                    "Things that help you fall asleep before bed",
                    "Makes you even more awake", "Asleep within 3 minutes",
                    "Three back-to-back horror movies right before bed", "A futon so fluffy it feels like sleeping on a cloud"),
                // 51
                new("二日酔いのときに食べやすいもの",
                    "絶対食べられない", "すぐ回復する",
                    "揚げたて激辛唐揚げ", "謎の薬草師の回復スープ",
                    "Food easy to eat when hungover",
                    "Impossible to eat", "Recover almost instantly",
                    "Just-fried extra-spicy chicken", "A recovery soup made by a mysterious herbalist"),
                // 52
                new("子どもが喜ぶおやつ",
                    "子どもが泣き出す", "大喜びで飛び回る",
                    "砂糖ゼロの苦いゼリー", "夢のケーキ食べ放題工場",
                    "Snacks that kids love",
                    "Kids start crying", "Kids leap for joy",
                    "Zero-sugar, intensely bitter jelly", "A dream cake factory where you can eat anything you want"),
                // 53
                new("忙しいときに助かるもの・サービス",
                    "余計に忙しくなる", "時間が生まれる",
                    "さらに増え続ける頼みごと", "全自動タスクこなすAI",
                    "Things or services that help when you're busy",
                    "Makes you even busier", "Creates extra time",
                    "An ever-growing mountain of requests that never stops", "An AI that automatically handles every task"),
                // 54
                new("冬に食べたい温かいもの",
                    "全然温まらない", "体の芯まで温まる",
                    "冷え冷えの昨日のご飯", "雪山の山小屋の猪鍋",
                    "Warm foods you want to eat in winter",
                    "No warmth whatsoever", "Warm to the very core",
                    "Ice-cold leftover rice from yesterday", "Wild boar hot pot in a snowy mountain hut"),
                // 55
                new("日曜の朝に楽しいもの・こと",
                    "最悪な気分になる", "最高に幸せ",
                    "朝5時に鳴る緊急の電話", "海が見える露天で朝食",
                    "Enjoyable things on a Sunday morning",
                    "Makes your morning awful", "Pure bliss",
                    "An emergency phone call ringing at 5 in the morning", "Breakfast in an open-air space overlooking the ocean"),
                // 56
                new("初対面の人と仲良くなれるもの・こと",
                    "むしろ距離が開く", "一瞬で打ち解ける",
                    "無言でひたすら見つめる", "奇跡の共通マイナー趣味",
                    "Things that help you bond with someone you just met",
                    "Pushes people even further away", "Instant best friends",
                    "Silently staring at them without saying a word", "A miraculously specific shared niche hobby"),
                // 57
                new("困ったときに頼りになる人の特徴",
                    "全然頼りにならない", "完璧に助けてくれる",
                    "即座に「無理」と言う人", "5分で全解決する達人",
                    "Traits of a reliable person when you're in trouble",
                    "Completely unreliable", "Solves everything perfectly",
                    "Someone who immediately says 'Impossible'", "A master who resolves everything in 5 minutes"),
                // 58
                new("ハイキングに持っていくと役立つもの",
                    "全く役立たない", "これで安心",
                    "ヒールの高いサンダル", "超軽量の万能登山靴",
                    "Things useful to bring on a hike",
                    "Completely useless", "Feel fully prepared",
                    "High-heeled sandals", "Ultra-lightweight all-terrain hiking shoes"),
                // 59
                new("記憶に残る嬉しい体験",
                    "すぐ忘れる", "一生忘れない",
                    "コンビニのポイント付与", "旅先での運命の出会い",
                    "Happy experiences that stay in your memory",
                    "Forget immediately", "Remember for life",
                    "Earning a few convenience store points", "A fateful encounter that changes everything while traveling"),
                // 60
                new("料理が得意な人が作ってくれると嬉しいもの",
                    "全然嬉しくない", "感動して泣く",
                    "蛇口から出た水だけ", "幻の高級食材の料理",
                    "Dishes you'd love a good cook to make for you",
                    "Not happy at all", "Moved to tears",
                    "Just water straight from the tap", "A dish made entirely from legendary rare ingredients"),
                // 61
                new("気分転換になるもの・こと",
                    "全然気分転換にならない", "完全にリフレッシュ",
                    "同じ場所でただ深呼吸", "誰も知らない秘密の海岸",
                    "Things that help you change your mood",
                    "No change at all", "Completely refreshed",
                    "Just taking a deep breath in the exact same spot", "A secret beach that nobody else has ever found"),
                // 62
                new("道に迷ったときに助かるもの",
                    "余計に迷う", "すぐ解決する",
                    "真っ白な地図", "全てを知る謎の案内人",
                    "Things that help when you're lost",
                    "Makes you even more lost", "Solved immediately",
                    "A completely blank map", "A mysterious guide who knows everything"),
                // 63
                new("子どもが夢中になれるもの",
                    "子どもが泣き出す", "時間を忘れる",
                    "夏休みの宿題ドリル", "本物の虫博士と昆虫採集",
                    "Things kids get completely absorbed in",
                    "Kids start crying", "Kids lose all track of time",
                    "Summer vacation homework drills", "Bug collecting with a real entomology professor"),
                // 64
                new("プロポーズで感動できるもの・こと",
                    "むしろ引いてしまう", "一生の宝物になる",
                    "くしゃくしゃのレシート", "貸切の星空でサプライズ",
                    "Proposal gestures that are truly moving",
                    "Creepy or off-putting", "A memory to treasure for life",
                    "A crumpled-up receipt", "A surprise proposal under a private starry sky"),
                // 65
                new("老人ホームで楽しめるもの・こと",
                    "全然楽しめない", "毎日やりたい",
                    "一人で天井を見つめる時間", "本物のプロのミニライブ",
                    "Things elderly people can enjoy at a care home",
                    "Not enjoyable at all", "Want to do it every day",
                    "Time spent alone doing nothing but staring at the ceiling", "A mini live concert by a real professional musician"),
                // 66
                new("二人でいると楽しい時間",
                    "一人の方がいい", "ずっとこのままでいたい",
                    "無言でスマホを見る時間", "朝まで話が尽きない夜",
                    "Time that's fun when spent with someone",
                    "Better alone", "Want it to last forever",
                    "Time spent silently looking at phones side by side", "A night where the conversation never runs out until dawn"),
                // 67
                new("コスパが良くて嬉しいもの・サービス",
                    "完全に損をする", "信じられないお得",
                    "翌日に壊れた300円傘", "格安で泊まれる絶景の宿",
                    "Things or services with great value for money",
                    "Total waste of money", "Unbelievable bargain",
                    "A 300-yen umbrella that breaks the very next day", "A jaw-dropping inn you can stay at for almost nothing"),
                // 68
                new("子どもに残してあげたいもの",
                    "全然残したくない", "最高の贈り物",
                    "読めない古い書類の山", "自分の体験を綴った日記",
                    "Things you'd want to leave behind for your children",
                    "Would never leave this", "The greatest gift",
                    "A pile of unreadable old documents", "A diary filled with every experience of your life"),
                // 69
                new("外食で頼みたいもの",
                    "絶対頼みたくない", "毎回頼む",
                    "お湯だけ注文する", "幻の食材の名物コース",
                    "Dishes you'd want to order at a restaurant",
                    "Would never order", "Order it every single time",
                    "Just ordering plain hot water", "A signature full-course meal made from legendary ingredients"),
                // 70
                new("春に楽しめるもの・こと",
                    "全然楽しめない", "最高の季節",
                    "花粉症で1日中くしゃみ", "秘密の満開桜を独り占め",
                    "Things you can enjoy in spring",
                    "Not enjoyable at all", "Best season of the year",
                    "Sneezing all day long from hay fever", "Having an entire secret cherry blossom grove all to yourself"),
                // 71
                new("インドア派が楽しめるもの・こと",
                    "全然楽しめない", "永遠にいられる",
                    "壁のしみを一晩数える", "伝説のゲームを全クリア",
                    "Things indoor people can enjoy",
                    "Not enjoyable indoors", "Could stay inside forever",
                    "Counting wall stains all through the night", "Completing a legendary game 100%"),
                // 72
                new("アウトドア派が楽しめるもの・こと",
                    "全然楽しめない", "一日中いられる",
                    "部屋でゴロゴロするだけ", "誰も踏んでいない山頂へ",
                    "Things outdoor lovers can enjoy",
                    "Not enjoyable outside", "Could stay out all day",
                    "Just lounging around in a room all day", "Standing on a summit nobody has ever reached before"),
                // 73
                new("仕事終わりに嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "帰り際に始まる土砂降り", "幻の名店で同僚と乾杯",
                    "Things you're happy about after finishing work",
                    "Not happy at all", "Absolute bliss",
                    "A torrential downpour that starts right as you leave", "Toasting with coworkers at a legendary restaurant"),
                // 74
                new("寒い日に外出したくなるもの・こと",
                    "絶対外出したくない", "すぐ飛び出す",
                    "猛吹雪の中のゴミ捨て", "誰も知らない冬の夜市",
                    "Things that make you want to go outside on a cold day",
                    "Would never go out", "Rush outside instantly",
                    "Taking out the garbage in the middle of a fierce blizzard", "A secret winter night market nobody knows about"),
                // 75
                new("停電の夜に楽しめること",
                    "全然楽しくない", "最高に楽しい",
                    "暗闇でひたすら正座する", "ろうそくで語り明かす夜",
                    "Things you can enjoy during a blackout at night",
                    "Not fun at all", "Best night of the year",
                    "Sitting perfectly still in complete darkness all night", "Talking until dawn by candlelight"),
                // 76
                new("カラオケで盛り上がれるもの・こと",
                    "全員が静まり返る", "大合唱になる",
                    "無音でひたすら立つ", "全員が奇跡の完璧ハモり",
                    "Things that make karaoke exciting",
                    "Everyone goes completely silent", "Everyone sings along",
                    "Just standing there in total silence", "A miraculous moment when everyone harmonizes perfectly"),
                // 77
                new("誕生日パーティーで盛り上がる出し物",
                    "場が完全に凍りつく", "爆発的に盛り上がる",
                    "領収書の読み上げタイム", "本物の火吹きジャグラー",
                    "Performances that hype up a birthday party",
                    "The whole room freezes in silence", "Crowd goes absolutely wild",
                    "A session of reading receipts aloud", "A real fire-breathing juggler"),
                // 78
                new("家の中でできる楽しいこと",
                    "全然楽しくない", "ずっとできる",
                    "壁のしみを全部数える", "1日かけて作る本格料理",
                    "Fun things you can do inside the house",
                    "Not fun at all", "Could do it all day",
                    "Counting every single stain on every wall", "Spending an entire day making a genuine gourmet meal"),
                // 79
                new("風邪をひいたときに助かるもの",
                    "全然助からない", "一瞬で治る",
                    "生の唐辛子をかじる", "謎の薬草師の特製スープ",
                    "Things that help when you have a cold",
                    "No help at all", "Heals in an instant",
                    "Biting into raw chili peppers", "A special soup from a mysterious herbalist"),
                // 80
                new("勉強のやる気が出るもの・こと",
                    "やる気が完全に消える", "集中が続く",
                    "突然届く宿題の追加", "尊敬する人からの一言",
                    "Things that motivate you to study",
                    "Kills all motivation completely", "Stay focused for hours",
                    "Extra homework suddenly appearing", "A single word of encouragement from someone you deeply respect"),
                // 81
                new("友達と過ごす休日に楽しいこと",
                    "全然楽しくない", "最高の一日",
                    "互いに無言でスマホ", "思いつきで行く隠れ絶景",
                    "Fun things to do with friends on a day off",
                    "Not fun at all", "Best day ever",
                    "Both silently scrolling phones next to each other", "A spontaneous trip to a hidden breathtaking spot"),
                // 82
                new("学校や会社に行くのが楽しみになる嬉しいこと",
                    "全然楽しみじゃない", "飛び起きる",
                    "今日怒られる確信がある", "大好きな人と話せる予定",
                    "Things that make you excited to go to school or work",
                    "Dread going", "Jump out of bed",
                    "The certainty that you'll get scolded today", "Plans to talk with someone you're in love with"),
                // 83
                new("旅行の思い出として嬉しいもの",
                    "全然嬉しくない", "一生の宝物",
                    "コンビニのレシートだけ", "地元の人だけ知る穴場",
                    "Things you'd be happy to have as travel memories",
                    "Not happy at all", "Treasure it for life",
                    "Nothing but a convenience store receipt", "A hidden gem only locals know about"),
                // 84
                new("年末年始に楽しめるもの・こと",
                    "全然楽しくない", "最高に楽しい",
                    "大みそかに届く宿題の山", "家族みんなの特大おせち",
                    "Things you can enjoy over New Year",
                    "Not enjoyable at all", "Best time of year",
                    "A huge pile of homework that arrives on New Year's Eve", "A massive New Year's feast with the whole family"),
                // 85
                new("一人旅で嬉しいもの・こと",
                    "全然嬉しくない", "最高の体験",
                    "乗り継ぎを3回連続失敗", "旅先で運命の人に出会う",
                    "Happy things about traveling alone",
                    "Not happy at all", "Life-changing experience",
                    "Missing your connection three times in a row", "Meeting the person of your destiny while traveling"),
                // 86
                new("運動会のお昼ご飯として嬉しいもの",
                    "全然嬉しくない", "最高においしい",
                    "水だけで乗り切る昼", "プロが作った特製弁当",
                    "Happy lunches at a school sports day",
                    "Not happy at all", "Absolutely delicious",
                    "Getting through lunch on just water", "A specially crafted bento made by a professional chef"),
                // 87
                new("暇つぶしになるもの・こと",
                    "全然暇つぶしにならない", "時間を忘れる",
                    "天井のしみを数える", "大好きな漫画の大人買い",
                    "Things that help pass the time",
                    "No help at all", "Lose all track of time",
                    "Counting stains on the ceiling", "Buying every single volume of your favorite manga at once"),
                // 88
                new("引っ越しのとき助かるもの・こと",
                    "全然助からない", "あっという間に終わる",
                    "ダンボールが1枚しかない", "全て任せる超丁寧な業者",
                    "Things that help when moving to a new place",
                    "No help at all", "Done before you know it",
                    "Having only a single cardboard box", "A meticulous full-service moving company that handles everything"),
                // 89
                new("子育てで楽しい瞬間",
                    "全然楽しくない", "最高に幸せ",
                    "深夜3時のおむつ替え", "初めて名前を呼ばれた日",
                    "Joyful moments in raising a child",
                    "Not enjoyable at all", "Greatest happiness in life",
                    "Changing diapers at 3 in the morning", "The day they called your name for the very first time"),
                // 90
                new("悲しいときに元気が出るもの・こと",
                    "むしろ落ち込む", "すぐ元気になる",
                    "さらに悲しいニュース", "親友に話を聞いてもらう",
                    "Things that cheer you up when you're sad",
                    "Makes you feel even worse", "Cheers you up instantly",
                    "Even sadder news on top of everything", "Your best friend showing up to listen"),
                // 91
                new("仕事で達成感があるもの・こと",
                    "全然達成感ない", "最高の達成感",
                    "ホチキスの針の補充だけ", "全員で乗り越えた大仕事",
                    "Work tasks that give a sense of accomplishment",
                    "No satisfaction at all", "Greatest satisfaction ever",
                    "Just refilling the stapler", "A huge project that the entire team overcame together"),
                // 92
                new("記念日のサプライズとして嬉しいもの",
                    "全然嬉しくない", "号泣するほど嬉しい",
                    "割り箸を1膳渡すだけ", "二人の思い出の場所に旅",
                    "Surprises you'd love to receive on an anniversary",
                    "Not happy at all", "Cry with joy",
                    "Handing them a single pair of disposable chopsticks", "A surprise trip to a place full of shared memories"),
                // 93
                new("二日酔いのときに助かるもの",
                    "余計につらくなる", "すぐ回復する",
                    "さらに飲み続ける悪循環", "薬草師の秘伝の回復茶",
                    "Things that help when you're hungover",
                    "Makes it much worse", "Recover almost instantly",
                    "Continuing to drink in a vicious cycle", "A secret recovery tea from an herbalist's ancient recipe"),
                // 94
                new("秋に楽しめるもの・こと",
                    "全然楽しくない", "最高の季節",
                    "落ち葉だらけの道を掃く", "誰も知らない紅葉の名所",
                    "Things you can enjoy in autumn",
                    "Not enjoyable at all", "Best season of the year",
                    "Sweeping a road completely buried in fallen leaves", "A secret autumn foliage spot nobody else knows about"),
                // 95
                new("お風呂上がりに嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "縮んだ使い古しのタオル", "極上のふかふかローブ",
                    "Happy things after getting out of the bath",
                    "Not happy at all", "Absolute bliss",
                    "A shrunken, worn-out old towel", "An ultra-luxurious fluffy bathrobe"),
                // 96
                new("寝坊した朝に助かるもの・こと",
                    "全然助からない", "間に合ってしまう",
                    "渋滞ひどいとのニュース", "寝坊した日が実は休日",
                    "Things that help when you've overslept",
                    "No help at all", "Somehow still make it",
                    "News that traffic is at a complete standstill", "Realising the day you overslept is actually a holiday"),
                // 97
                new("お正月に嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "お年玉が10円だった衝撃", "親戚全員からのお年玉",
                    "Happy things about New Year",
                    "Not happy at all", "Pure happiness",
                    "The shock of receiving only 10 yen as New Year's money", "New Year's money from every single relative"),
                // 98
                new("冬のデートで楽しいもの・場所",
                    "全然楽しくない", "一生の思い出",
                    "猛吹雪の中の立ち話", "二人だけの秘密の夜景",
                    "Fun things or places for a winter date",
                    "Not fun at all", "A memory for life",
                    "Chatting while standing in a fierce blizzard", "A secret night view spot just for the two of you"),
                // 99
                new("大切な人への気持ちを伝えるもの・方法",
                    "全然伝わらない", "完璧に伝わる",
                    "レシートをそっと渡す", "何年もかけて書いた手紙",
                    "Ways to express your feelings to someone special",
                    "Feeling not conveyed at all", "Perfectly understood",
                    "Quietly slipping them a receipt", "A letter you spent years writing"),
                // 100
                new("人生を振り返って一番嬉しかった体験",
                    "全く嬉しくなかった", "最高に嬉しかった",
                    "財布の隅の小銭を発見", "子どもが結婚した日の涙",
                    "The happiest experience when you look back on life",
                    "Not happy at all", "The greatest joy in life",
                    "Finding a few coins in the corner of your wallet", "The tears of joy on the day your child got married"),
            };
        }
    }
}
