using System.Collections.Generic;
using UnityEngine;

namespace BomBomLemon.Game.Topics
{
    [CreateAssetMenu(fileName = "TopicDatabase", menuName = "BomBom Lemon/Topic Database", order = 1)]
    public class TopicDatabase : ScriptableObject
    {
        [SerializeField] private List<Topic> topics = new();

        public IReadOnlyList<Topic> Topics => topics;

        public Topic GetRandom()
        {
            if (topics.Count == 0) return FallbackTopic();
            return topics[Random.Range(0, topics.Count)];
        }

        static Topic FallbackTopic() => new(
            "好きな食べ物の甘さ", "甘くない", "めちゃ甘い", "塩昆布", "砂糖まみれのスイーツ",
            "Sweetness of your fav food", "Not sweet", "Extremely sweet", "Salted kelp", "Sugar-coated everything"
        );

        [ContextMenu("Load Default Japanese Topics")]
        void LoadDefaultTopics()
        {
            topics = new List<Topic>
            {
                // 1
                new("誕生日にもらって嬉しいもの",
                    "全く嬉しくない", "最高に嬉しい",
                    "他人の名刺1枚だけ", "謎の富豪からの小切手",
                    "Things you're happy to receive for your birthday",
                    "Not happy at all", "Overjoyed",
                    "Someone else's business card", "A cheque from a mysterious millionaire"),
                // 2
                new("空腹のときに食べたいもの",
                    "食欲ゼロ", "最高においしい",
                    "3日前の乾いたパン", "幻の高級トリュフ料理",
                    "Things you want to eat when starving",
                    "Zero appetite", "Absolutely delicious",
                    "3-day-old dried bread", "A legendary truffle dish"),
                // 3
                new("夏に涼しくなれるもの・こと",
                    "全然涼しくない", "極限まで涼しい",
                    "風のない日のうちわ", "北極の氷の洞窟で昼寝",
                    "Things that cool you down in summer",
                    "No coolness at all", "Perfectly chilled",
                    "A paper fan on a windless day", "Napping in an Arctic ice cave"),
                // 4
                new("子どものころに欲しかったもの",
                    "全然欲しくなかった", "死ぬほど欲しかった",
                    "地味な文房具セット", "等身大の変身ロボット",
                    "Things you wanted as a child",
                    "Didn't want at all", "Desperately wanted",
                    "A boring stationery set", "A life-sized transformation robot"),
                // 5
                new("旅行先として行きたい場所",
                    "絶対行きたくない", "今すぐ行きたい",
                    "誰も知らない無名の駅", "地図にない秘密の島",
                    "Places you want to visit as a travel destination",
                    "Never want to go", "Want to go right now",
                    "An unknown station nobody visits", "A secret island not on any map"),
                // 6
                new("疲れたときに癒されるもの・こと",
                    "全然癒されない", "完全に癒される",
                    "固いせんべい布団", "雲の上のスパで1泊",
                    "Things that heal you when you're exhausted",
                    "Not relaxing at all", "Fully restored",
                    "A hard crackerlike futon", "One night at a spa above the clouds"),
                // 7
                new("朝起きるのが楽しみになるもの",
                    "全然楽しみじゃない", "飛び起きる",
                    "冷蔵庫が空の朝", "宝くじ1等当選の朝",
                    "Things that make you excited to wake up",
                    "Dread waking up", "Jump out of bed",
                    "Morning with an empty fridge", "Morning you won the lottery jackpot"),
                // 8
                new("無人島に持っていったら役立つもの",
                    "全く役に立たない", "命が救われる",
                    "ハイヒールとネクタイ", "全自動サバイバルAI",
                    "Things useful to bring to a deserted island",
                    "Completely useless", "Life-saving",
                    "High heels and a necktie", "A fully automatic survival AI"),
                // 9
                new("友達に紹介したいもの・こと",
                    "紹介したくない", "絶対紹介したい",
                    "近所の工事現場の騒音", "人生が変わる秘密の場所",
                    "Things you want to recommend to friends",
                    "Would never recommend", "Must share with everyone",
                    "The noise from a construction site nearby", "A secret place that changes your life"),
                // 10
                new("寒い冬に温まれるもの・こと",
                    "全然温まらない", "芯まで温まる",
                    "穴あきの薄い手袋", "火山脇の絶景露天風呂",
                    "Things that warm you up in cold winter",
                    "No warmth at all", "Warm to the core",
                    "Thin gloves full of holes", "An open-air bath with a volcano view"),
                // 11
                new("お腹が痛いときに助かるもの",
                    "全然助からない", "すぐ楽になる",
                    "ただの深呼吸だけ", "飲んだら即治る薬草茶",
                    "Things that help when you have a stomachache",
                    "No help at all", "Instant relief",
                    "Just taking a deep breath", "An herbal tea that heals you instantly"),
                // 12
                new("子どもに人気がありそうなもの",
                    "子どもが嫌がる", "取り合いになる",
                    "虫食いの算数ドリル", "空飛ぶ遊園地の乗り物",
                    "Things that seem popular with kids",
                    "Kids want nothing to do with it", "Kids fight over it",
                    "A moth-eaten math drill", "A flying amusement park ride"),
                // 13
                new("大人になってよかったと感じる嬉しいこと",
                    "全然よくない", "大人で本当によかった",
                    "自分で歯磨きする権利", "誰にも門限を言われない",
                    "Good things about being an adult",
                    "Not good at all", "So glad to be an adult",
                    "The right to brush your own teeth", "Nobody tells you when to come home"),
                // 14
                new("雨の日に気分が上がるもの・こと",
                    "気分が下がる", "最高に上がる",
                    "泥が跳ねる白い靴", "雨音のBGMで読書",
                    "Things that lift your mood on a rainy day",
                    "Makes mood worse", "Best mood ever",
                    "White shoes with mud splashing everywhere", "Reading with rain sounds as a soundtrack"),
                // 15
                new("運動会で盛り上がる競技",
                    "全然盛り上がらない", "最高に盛り上がる",
                    "正座で耐える耐久戦", "全員が空を飛ぶリレー",
                    "Sports-day events that get everyone excited",
                    "Dead silent", "Crowd goes wild",
                    "An endurance sitting-still contest", "A relay race where everyone flies"),
                // 16
                new("もらって嬉しいサプライズ",
                    "全然嬉しくない", "号泣するほど嬉しい",
                    "使いかけのリップ", "伝説のシェフの料理",
                    "Surprises you'd be happy to receive",
                    "Not happy at all", "Cry with joy",
                    "A half-used lip balm", "A meal cooked by a legendary chef"),
                // 17
                new("ペットにするとかわいいいきもの",
                    "全然かわいくない", "最高にかわいい",
                    "近所のドブネズミ", "手乗りサイズのシャチ",
                    "Creatures that would be cute as pets",
                    "Not cute at all", "Absolutely adorable",
                    "A sewer rat from the neighborhood", "A palm-sized killer whale"),
                // 18
                new("老後に楽しめそうなもの・こと",
                    "全然楽しめない", "毎日やりたい",
                    "税金の見直し作業", "月に別荘を持って住む",
                    "Things you could enjoy in retirement",
                    "Not enjoyable", "Want to do it every day",
                    "Reviewing old tax documents", "Living in a villa on the moon"),
                // 19
                new("引っ越し先として住みやすそうな場所",
                    "全然住みたくない", "すぐ引っ越したい",
                    "線路の真上の1K", "崖の上のガラス張りの家",
                    "Places that seem easy and pleasant to live in",
                    "Would never live there", "Moving in right now",
                    "A tiny apartment directly above a train track", "A glass house perched on a cliff"),
                // 20
                new("記念日に食べたいごちそう",
                    "全然食べたくない", "最高においしい",
                    "賞味期限切れカレー", "伝説の職人の特製寿司",
                    "Dishes you'd want for a special occasion",
                    "Not appetizing at all", "Best meal ever",
                    "Expired canned curry", "Hand-crafted sushi from a legendary chef"),
                // 21
                new("試験勉強がはかどるもの・環境",
                    "全然はかどらない", "10倍速で覚えられる",
                    "爆音パチンコ店の隣", "記憶が10倍になる椅子",
                    "Environments or things that help you study",
                    "Zero focus", "Memorize 10x faster",
                    "Sitting next to a blaring pachinko parlor", "A chair that multiplies your memory 10x"),
                // 22
                new("プレゼントとして贈りやすいもの",
                    "絶対贈れない", "誰でも喜ぶ",
                    "使いかけの赤ペン1本", "その人の名前入りの星",
                    "Things easy to give as a gift",
                    "Can never give this", "Everyone loves it",
                    "One half-used red pen", "A star named after them"),
                // 23
                new("子どもに読み聞かせたい絵本のテーマ",
                    "絶対読まない", "毎晩読みたい",
                    "住民税の計算方法", "謎の生き物と旅する話",
                    "Themes for picture books to read to children",
                    "Would never read", "Read it every night",
                    "How to calculate residential tax", "An adventure story with a mysterious creature"),
                // 24
                new("長い列に並んで待ってでも食べたい食べ物",
                    "並ぶ気ゼロ", "3時間並んでも食べたい",
                    "何の味もしない白湯", "幻の職人の特製ラーメン",
                    "Food worth waiting in a long line for",
                    "Not worth any wait", "Worth a 3-hour wait",
                    "Flavorless hot water", "A legendary ramen made by a secret master"),
                // 25
                new("雨の日の楽しい過ごし方",
                    "全然楽しくない", "最高に楽しい",
                    "傘を忘れて全力疾走", "特等席で嵐を鑑賞する",
                    "Fun ways to spend a rainy day",
                    "Not fun at all", "Best day ever",
                    "Forgetting your umbrella and sprinting", "Watching a storm from a front-row seat"),
                // 26
                new("デートで行きたい場所",
                    "絶対行きたくない", "今すぐ行きたい",
                    "区役所の待合室", "秘密の絶景スポット",
                    "Places you'd want to go on a date",
                    "Never going there on a date", "Going right now",
                    "The waiting room at city hall", "A secret spot with a breathtaking view"),
                // 27
                new("家にあったら便利なもの",
                    "全然便利じゃない", "生活が激変する",
                    "使わない傘が50本", "言葉を聞く掃除ロボット",
                    "Things that would be convenient to have at home",
                    "Not convenient at all", "Life completely transforms",
                    "50 umbrellas you never use", "A cleaning robot that understands speech"),
                // 28
                new("夜ご飯に食べたいもの",
                    "食欲ゼロ", "最高においしい",
                    "昨日のカチカチのご飯", "幻の料亭の秘伝の鍋",
                    "Things you want to eat for dinner",
                    "Zero appetite", "Absolutely delicious",
                    "Yesterday's rock-hard leftover rice", "A secret hot pot from a legendary inn"),
                // 29
                new("子どもに習わせたいスキル・習い事",
                    "全然習わせたくない", "絶対習わせたい",
                    "ハンコの正しい押し方", "動物と話せる言語",
                    "Skills or lessons you'd want your child to learn",
                    "Would never teach this", "Must learn this",
                    "How to properly stamp a personal seal", "A language for talking to animals"),
                // 30
                new("ストレス解消になるもの・こと",
                    "全然解消されない", "スッキリ消える",
                    "壁に向かって独り言", "誰もいない島で叫ぶ",
                    "Things that relieve stress",
                    "No relief at all", "Stress vanishes instantly",
                    "Talking to yourself facing a wall", "Screaming on a deserted island"),
                // 31
                new("キャンプで役立つもの",
                    "全く役立たない", "なければ困る",
                    "ピンヒールのサンダル", "自動で何でも作るコンロ",
                    "Things useful for camping",
                    "Completely useless", "Can't camp without it",
                    "Stiletto-heeled sandals", "A stove that automatically cooks anything"),
                // 32
                new("体調不良のときに食べやすいもの",
                    "絶対食べられない", "すぐ元気になる",
                    "激辛の唐辛子ラーメン", "謎の薬草師のお粥",
                    "Things easy to eat when you're feeling sick",
                    "Impossible to eat", "Recover quickly",
                    "Extra-hot chili ramen", "Porridge from a mysterious herbalist"),
                // 33
                new("100円で買える嬉しいもの",
                    "全然嬉しくない", "信じられないほど嬉しい",
                    "汚れた消しゴム1個", "激レアの当たり商品",
                    "Things you'd be happy to buy for 100 yen",
                    "Not happy at all", "Unbelievably happy",
                    "One dirty eraser", "An ultra-rare winning item"),
                // 34
                new("働くモチベーションが上がるもの・こと",
                    "全然上がらない", "喜んで残業できる",
                    "追加の深夜残業通知", "突然の給料2倍の通知",
                    "Things that boost your motivation to work",
                    "No motivation boost", "Could work all night with a smile",
                    "Notification of extra midnight overtime", "Sudden notification your salary doubled"),
                // 35
                new("部屋に飾りたいもの",
                    "絶対飾りたくない", "部屋が映える",
                    "空になったダンボール", "波に磨かれた流木アート",
                    "Things you'd want to decorate your room with",
                    "Would never display this", "Makes the room look amazing",
                    "Empty cardboard boxes", "Driftwood art polished by the waves"),
                // 36
                new("眠れない夜に役立つもの・こと",
                    "余計に目が冴える", "すぐ眠くなる",
                    "3本目のコーヒー", "眠りに落ちる謎の音楽",
                    "Things that help when you can't sleep",
                    "Makes you even more awake", "Gets you sleepy fast",
                    "Your third cup of coffee", "A mysterious song that makes you fall asleep"),
                // 37
                new("子どもに人気の遊び",
                    "全然人気ない", "みんなが集まる",
                    "漢字の書き取りドリル", "夜光る謎のボールで遊ぶ",
                    "Games and activities popular with kids",
                    "Kids ignore it", "All the kids gather around",
                    "Kanji writing drill worksheets", "Playing with mysterious glowing balls"),
                // 38
                new("老後にやってみたいこと",
                    "全然やりたくない", "絶対やりたい",
                    "書類の山を整理する", "世界の絶景を全制覇",
                    "Things you'd want to try in retirement",
                    "Never want to do", "Absolutely must do",
                    "Sorting through a mountain of old documents", "Visiting every breathtaking view in the world"),
                // 39
                new("コンビニで買える嬉しいもの",
                    "全然嬉しくない", "最高に嬉しい",
                    "袋だけ購入する", "万券が当たるスクラッチ",
                    "Things you'd be happy to buy at a convenience store",
                    "Not happy at all", "Best feeling ever",
                    "Just buying a plastic bag", "A scratch card that wins you ten thousand yen"),
                // 40
                new("長距離ドライブのお供になるもの",
                    "全然盛り上がらない", "最高のドライブになる",
                    "全チャンネル無音状態", "旅の神様が選んだBGM",
                    "Things that make a long road trip better",
                    "No help at all", "Best drive of your life",
                    "Total silence on every channel", "A playlist chosen by the god of travel"),
                // 41
                new("お花見で盛り上がるもの・こと",
                    "全然盛り上がらない", "最高に盛り上がる",
                    "お弁当なしで正座", "散る夜桜の絶景の席",
                    "Things that make cherry blossom viewing exciting",
                    "No excitement at all", "Best outdoor party ever",
                    "Sitting on the ground with no food", "A front-row seat under falling night sakura"),
                // 42
                new("一人で楽しめるもの・こと",
                    "全然楽しめない", "永遠にできる",
                    "壁のしみを数え続ける", "幻のプライベート映画祭",
                    "Things you can enjoy alone",
                    "Not enjoyable solo", "Could do it forever",
                    "Endlessly counting stains on the wall", "A phantom private film festival"),
                // 43
                new("子どもの誕生日パーティーで喜ばれるもの",
                    "子どもが凍りつく", "大興奮で喜ぶ",
                    "当日届いた宿題プリント", "プロのマジシャンの実演",
                    "Things kids would love at a birthday party",
                    "Kids go silent in horror", "Kids go absolutely wild",
                    "Homework printouts delivered on the day", "A live show by a professional magician"),
                // 44
                new("海外旅行で買いたいお土産",
                    "絶対買いたくない", "絶対買って帰りたい",
                    "現地の古いレシート", "世界に1個だけのアクセ",
                    "Souvenirs you'd want to buy on a trip abroad",
                    "Would never buy", "Must bring home",
                    "An old receipt from a local shop", "A one-of-a-kind accessory in the world"),
                // 45
                new("運動不足解消になるもの・こと",
                    "全然解消されない", "体が変わる",
                    "ベッドで寝返りだけ", "専属コーチが毎日来る",
                    "Things that help fix lack of exercise",
                    "No effect at all", "Body completely transforms",
                    "Just rolling over in bed", "A personal coach who shows up every day"),
                // 46
                new("二人で食べると美味しいもの",
                    "一人で食べた方がいい", "二人だと倍旨い",
                    "半分に割った薄いガム", "初めて二人で作った鍋",
                    "Food that tastes better when shared with someone",
                    "Better to eat alone", "Twice as delicious together",
                    "Splitting a thin piece of gum in half", "A hot pot you made together for the first time"),
                // 47
                new("家族で楽しめるもの・こと",
                    "家族でやりたくない", "家族の絆が深まる",
                    "確定申告の書類整理", "家族全員でやるRPG",
                    "Things the whole family can enjoy together",
                    "Family would never do this", "Deepens family bonds",
                    "Sorting through tax return documents", "An RPG the whole family plays together"),
                // 48
                new("友達と盛り上がれるゲーム",
                    "全然盛り上がらない", "夜通しできる",
                    "足し算競争のプリント", "謎の廃墟で宝探し",
                    "Games that get exciting with friends",
                    "No excitement", "Could play all night",
                    "A speed addition competition on paper", "A treasure hunt in a mysterious ruin"),
                // 49
                new("夏祭りで楽しいもの",
                    "全然楽しくない", "最高に楽しい",
                    "ゴミ袋係の担当", "花火師が隣にいる席",
                    "Fun things at a summer festival",
                    "Not fun at all", "Best night of the year",
                    "Being assigned the trash bag duty", "Sitting right next to the fireworks crew"),
                // 50
                new("寝る前にすると眠れるもの・こと",
                    "余計に眠れなくなる", "3分で熟睡できる",
                    "深夜にエナジードリンク", "聴いた瞬間眠れる音楽",
                    "Things that help you fall asleep before bed",
                    "Makes you even more awake", "Asleep within 3 minutes",
                    "An energy drink late at night", "A song that puts you to sleep the moment you hear it"),
                // 51
                new("二日酔いのときに食べやすいもの",
                    "絶対食べられない", "すぐ回復する",
                    "揚げたて激辛唐揚げ", "謎の薬草師の回復スープ",
                    "Food easy to eat when hungover",
                    "Impossible to eat", "Recover quickly",
                    "Just-fried extra-spicy chicken", "A recovery soup from a mysterious herbalist"),
                // 52
                new("子どもが喜ぶおやつ",
                    "全然喜ばない", "大喜びする",
                    "砂糖ゼロの苦いゼリー", "好きに作れるケーキ工場",
                    "Snacks that kids love",
                    "Kids hate it", "Kids are overjoyed",
                    "Zero-sugar bitter jelly", "A cake factory where you can make anything you want"),
                // 53
                new("忙しいときに助かるもの・サービス",
                    "余計に忙しくなる", "時間が生まれる",
                    "山積みタスクの追加通知", "全部やってくれるAI",
                    "Things or services that help when you're busy",
                    "Makes you even busier", "Creates extra time",
                    "Notification adding more tasks to the pile", "An AI that does everything for you"),
                // 54
                new("冬に食べたい温かいもの",
                    "全然温まらない", "体の芯まで温まる",
                    "冷え切った昨日のご飯", "雪山小屋の猪鍋",
                    "Warm foods you want to eat in winter",
                    "No warmth at all", "Warm to the core",
                    "Yesterday's cold leftover rice", "Wild boar hot pot in a snowy mountain hut"),
                // 55
                new("日曜の朝に楽しいもの・こと",
                    "全然楽しくない", "最高に幸せ",
                    "早朝に届く督促状", "オーシャンビューの朝食",
                    "Enjoyable things on a Sunday morning",
                    "Not enjoyable at all", "Pure bliss",
                    "A payment reminder arriving at dawn", "Breakfast with a view of the ocean"),
                // 56
                new("初対面の人と仲良くなれるもの・こと",
                    "むしろ距離が開く", "一瞬で打ち解ける",
                    "無言でずっと見つめる", "共通の謎のマイナー趣味",
                    "Things that help you bond with someone you just met",
                    "Pushes people even further away", "Instant best friends",
                    "Silently staring at them for a long time", "A weirdly specific shared niche hobby"),
                // 57
                new("困ったときに頼りになる人の特徴",
                    "全然頼りにならない", "完璧に助けてくれる",
                    "「それは無理」と言う人", "5分で何でも解決する人",
                    "Traits of a reliable person when you're in trouble",
                    "Not reliable at all", "Solves everything for you",
                    "Someone who always says 'That's impossible'", "Someone who solves anything in 5 minutes"),
                // 58
                new("ハイキングに持っていくと役立つもの",
                    "全く役立たない", "これで安心",
                    "ヒールの高いサンダル", "超軽量の万能登山ブーツ",
                    "Things useful to bring on a hike",
                    "Completely useless", "Feel fully prepared",
                    "High-heeled sandals", "Ultra-lightweight all-terrain hiking boots"),
                // 59
                new("記憶に残る嬉しい体験",
                    "すぐ忘れる", "一生忘れない",
                    "コンビニのポイント付与", "異国で奇跡の出来事",
                    "Happy experiences that stay in your memory",
                    "Forget immediately", "Remember for life",
                    "Earning a few convenience store points", "A miraculous event in a foreign country"),
                // 60
                new("料理が得意な人が作ってくれると嬉しいもの",
                    "全然嬉しくない", "感動して泣く",
                    "ぬるいお湯だけ", "幻の食材を使った料理",
                    "Dishes you'd love a good cook to make for you",
                    "Not happy at all", "Moved to tears",
                    "Just lukewarm water", "A dish made from legendary rare ingredients"),
                // 61
                new("気分転換になるもの・こと",
                    "全然気分転換にならない", "完全にリフレッシュ",
                    "同じ部屋で同じ深呼吸", "誰も知らない秘密の海岸",
                    "Things that help you change your mood",
                    "No change at all", "Completely refreshed",
                    "The same deep breath in the same room", "A secret beach nobody knows about"),
                // 62
                new("道に迷ったときに助かるもの",
                    "全然助からない", "すぐ解決する",
                    "真っ白な地図", "地元を熟知した住人",
                    "Things that help when you're lost",
                    "No help at all", "Solved right away",
                    "A completely blank map", "A local who knows every street by heart"),
                // 63
                new("子どもが夢中になれるもの",
                    "全然夢中にならない", "時間を忘れる",
                    "夏休みの宿題ドリル", "本物の虫博士と昆虫採集",
                    "Things kids get completely absorbed in",
                    "Kids ignore it", "Kids lose track of time",
                    "Summer vacation homework drills", "Bug hunting with a real entomologist"),
                // 64
                new("プロポーズで感動できるもの・こと",
                    "むしろ引いてしまう", "一生の宝物になる",
                    "スーパーのレシートだけ", "貸切の星空の下で",
                    "Proposal gestures that are truly moving",
                    "Creepy or off-putting", "A memory to treasure for life",
                    "Just handing them a supermarket receipt", "Under a private starry sky, just the two of you"),
                // 65
                new("老人ホームで楽しめるもの・こと",
                    "全然楽しめない", "毎日やりたい",
                    "税金書類の見直し作業", "プロのミニコンサート",
                    "Things elderly people can enjoy at a care home",
                    "Not enjoyable at all", "Want to do it every day",
                    "Reviewing old tax documents", "A mini concert by a professional musician"),
                // 66
                new("二人でいると楽しい時間",
                    "一人の方がいい", "ずっとこのままでいたい",
                    "黙ってスマホを見る時間", "夜中まで話が尽きない夜",
                    "Time that's fun when spent with someone",
                    "Better alone", "Want it to last forever",
                    "Time spent silently looking at phones", "A night when the conversation never runs out"),
                // 67
                new("コスパが良くて嬉しいもの・サービス",
                    "完全に損をする", "信じられないお得",
                    "翌日に壊れる300円の傘", "格安で泊まれる絶景の宿",
                    "Things or services with great value for money",
                    "Total waste of money", "Unbelievable bargain",
                    "A 300-yen umbrella that breaks the next day", "A stunning inn you can stay at for almost nothing"),
                // 68
                new("子どもに残してあげたいもの",
                    "全然残したくない", "最高の贈り物",
                    "古い雑誌だらけの本棚", "自分の体験を綴った日記",
                    "Things you'd want to leave behind for your children",
                    "Would never leave this", "The greatest gift",
                    "A bookshelf packed with old magazines", "A diary filled with your life experiences"),
                // 69
                new("外食で頼みたいもの",
                    "絶対頼みたくない", "毎回頼む",
                    "白湯のみ注文", "幻の食材で作った名物丼",
                    "Dishes you'd want to order at a restaurant",
                    "Would never order", "Order it every single time",
                    "Just ordering hot water", "A signature rice bowl made from legendary ingredients"),
                // 70
                new("春に楽しめるもの・こと",
                    "全然楽しめない", "最高の季節",
                    "花粉症で一日くしゃみ", "全国の桜の名所を制覇",
                    "Things you can enjoy in spring",
                    "Not enjoyable", "Best season of the year",
                    "Sneezing all day from hay fever", "Visiting every famous cherry blossom spot in Japan"),
                // 71
                new("インドア派が楽しめるもの・こと",
                    "全然楽しめない", "永遠にいられる",
                    "天井のしみを数え続ける", "伝説のゲームを全クリア",
                    "Things indoor people can enjoy",
                    "Not enjoyable indoors", "Could stay inside forever",
                    "Endlessly counting ceiling stains", "Completing a legendary game 100%"),
                // 72
                new("アウトドア派が楽しめるもの・こと",
                    "全然楽しめない", "一日中いられる",
                    "部屋でゴロゴロするだけ", "未踏の山の頂に立つ",
                    "Things outdoor lovers can enjoy",
                    "Not enjoyable outside", "Could stay out all day",
                    "Just lounging around indoors", "Standing on the summit of an unclimbed mountain"),
                // 73
                new("仕事終わりに嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "帰宅直前の緊急追加仕事", "幻の名店で同僚と乾杯",
                    "Things you're happy about after finishing work",
                    "Not happy at all", "Absolute bliss",
                    "Urgent extra work added just before leaving", "Toasting with coworkers at a legendary restaurant"),
                // 74
                new("寒い日に外出したくなるもの・こと",
                    "絶対外出したくない", "すぐ飛び出す",
                    "税務署への呼び出し状", "誰も知らない冬の夜市",
                    "Things that make you want to go outside on a cold day",
                    "Would never go out", "Rush outside instantly",
                    "A written summons from the tax office", "A secret winter night market nobody knows about"),
                // 75
                new("停電の夜に楽しめること",
                    "全然楽しくない", "最高に楽しい",
                    "暗闇でひたすら正座", "ろうそくで語り明かす夜",
                    "Things you can enjoy during a blackout at night",
                    "Not fun at all", "Best night of the year",
                    "Sitting perfectly still in complete darkness", "Talking the whole night through by candlelight"),
                // 76
                new("カラオケで盛り上がれるもの・こと",
                    "全然盛り上がらない", "大合唱になる",
                    "無音でひたすら立つ", "全員が奇跡のハモり",
                    "Things that make karaoke exciting",
                    "Total dead silence", "Everyone sings along",
                    "Just standing there in total silence", "A miraculous moment when everyone harmonizes perfectly"),
                // 77
                new("誕生日パーティーで盛り上がる出し物",
                    "場が凍りつく", "爆発的に盛り上がる",
                    "領収書の読み上げタイム", "本物の火吹きジャグラー",
                    "Performances that hype up a birthday party",
                    "Kills the vibe completely", "Crowd goes absolutely wild",
                    "A reading-receipts-aloud session", "A real fire-breathing juggler"),
                // 78
                new("家の中でできる楽しいこと",
                    "全然楽しくない", "ずっとできる",
                    "部屋の壁のしみを数える", "一日かけて作る本格料理",
                    "Fun things you can do inside the house",
                    "Not fun at all", "Could do it all day",
                    "Counting every stain on the walls", "Spending a whole day making a proper gourmet meal"),
                // 79
                new("風邪をひいたときに助かるもの",
                    "全然助からない", "すぐに楽になる",
                    "生のニンニクをまるごと", "謎の薬草師の特製スープ",
                    "Things that help when you have a cold",
                    "No help at all", "Feel better quickly",
                    "Eating a whole clove of raw garlic", "A special soup from a mysterious herbalist"),
                // 80
                new("勉強のやる気が出るもの・こと",
                    "やる気ゼロになる", "集中が続く",
                    "追加で届いた宿題の山", "尊敬する人からの一言",
                    "Things that motivate you to study",
                    "Kills all motivation", "Stay focused for hours",
                    "Another mountain of extra homework arriving", "A single word of encouragement from someone you admire"),
                // 81
                new("友達と過ごす休日に楽しいこと",
                    "全然楽しくない", "最高の一日",
                    "お互い黙ってスマホ", "思いつきで行く隠れ絶景",
                    "Fun things to do with friends on a day off",
                    "Not fun at all", "Best day ever",
                    "Both silently scrolling their phones", "An unplanned trip to a hidden breathtaking spot"),
                // 82
                new("学校や会社に行くのが楽しみになる嬉しいこと",
                    "全然楽しみじゃない", "飛び起きる",
                    "今日怒られる予感がある", "大好きな人に会える予定",
                    "Things that make you excited to go to school or work",
                    "Dread going", "Jump out of bed",
                    "The feeling you'll get scolded today", "Plans to see someone you're crazy about"),
                // 83
                new("旅行の思い出として嬉しいもの",
                    "全然嬉しくない", "一生の宝物",
                    "コンビニのレシートだけ", "地元の人だけ知る穴場",
                    "Things you'd be happy to have as travel memories",
                    "Not happy at all", "Treasure it for life",
                    "Nothing but a convenience store receipt", "A hidden gem only locals know about"),
                // 84
                new("年末年始に楽しめるもの・こと",
                    "全然楽しくない", "最高に楽しい",
                    "大晦日の確定申告作業", "家族と食べる特大おせち",
                    "Things you can enjoy over New Year",
                    "Not enjoyable at all", "Best time of year",
                    "Doing tax prep work on New Year's Eve", "A giant New Year's feast with the whole family"),
                // 85
                new("一人旅で嬉しいもの・こと",
                    "全然嬉しくない", "最高の体験",
                    "乗り継ぎに3回連続失敗", "偶然出会う旅の運命の人",
                    "Happy things about traveling alone",
                    "Not happy at all", "Life-changing experience",
                    "Missing your connection three times in a row", "A fateful encounter with a stranger on the road"),
                // 86
                new("運動会のお昼ご飯として嬉しいもの",
                    "全然嬉しくない", "最高においしい",
                    "水だけで乗り切る昼", "プロが作った特製お弁当",
                    "Happy lunches at a school sports day",
                    "Not happy at all", "Absolutely delicious",
                    "Getting through lunch on just water", "A specially crafted bento made by a professional chef"),
                // 87
                new("暇つぶしになるもの・こと",
                    "全然暇つぶしにならない", "時間を忘れる",
                    "天井のしみを数える", "大好きな漫画の大人買い",
                    "Things that help pass the time",
                    "No help at all", "Lose all track of time",
                    "Counting stains on the ceiling", "Buying every volume of your favorite manga at once"),
                // 88
                new("引っ越しのとき助かるもの・こと",
                    "全然助からない", "あっという間に終わる",
                    "ダンボールが1枚しかない", "全任せの超丁寧な業者",
                    "Things that help when moving to a new place",
                    "No help at all", "Done before you know it",
                    "Having only a single cardboard box", "A meticulous moving company that handles everything"),
                // 89
                new("子育てで楽しい瞬間",
                    "全然楽しくない", "最高に幸せ",
                    "深夜3時のおむつ替え", "初めて名前を呼ばれた日",
                    "Joyful moments in raising a child",
                    "Not enjoyable at all", "Greatest happiness in life",
                    "Changing diapers at 3 in the morning", "The day they called your name for the first time"),
                // 90
                new("悲しいときに元気が出るもの・こと",
                    "むしろ落ち込む", "すぐ元気になる",
                    "さらに悲しいニュース", "親友に電話して話す",
                    "Things that cheer you up when you're sad",
                    "Makes you feel even worse", "Cheers you up instantly",
                    "Even sadder news to add to your misery", "Calling your best friend to talk"),
                // 91
                new("仕事で達成感があるもの・こと",
                    "全然達成感ない", "最高の達成感",
                    "事務用品の在庫補充だけ", "全員で乗り越えた大仕事",
                    "Work tasks that give a sense of accomplishment",
                    "No satisfaction at all", "Greatest satisfaction ever",
                    "Just restocking office supplies", "A huge project the whole team overcame together"),
                // 92
                new("記念日のサプライズとして嬉しいもの",
                    "全然嬉しくない", "号泣するほど嬉しい",
                    "割り箸を1膳だけ渡す", "思い出の場所への旅",
                    "Surprises you'd love to receive on an anniversary",
                    "Not happy at all", "Cry with joy",
                    "Handing them a single pair of chopsticks", "A surprise trip to a place full of memories"),
                // 93
                new("二日酔いのときに助かるもの",
                    "余計につらくなる", "すぐ回復する",
                    "さらに飲み続ける悪循環", "薬草師の秘伝の回復茶",
                    "Things that help when you're hungover",
                    "Makes it much worse", "Recover quickly",
                    "Continuing to drink in a vicious cycle", "A secret recovery tea from an herbalist"),
                // 94
                new("秋に楽しめるもの・こと",
                    "全然楽しくない", "最高の季節",
                    "落ち葉だらけの道を掃く", "誰も知らない紅葉の名所",
                    "Things you can enjoy in autumn",
                    "Not enjoyable at all", "Best season of the year",
                    "Sweeping a path buried in fallen leaves", "A hidden autumn foliage spot nobody knows"),
                // 95
                new("お風呂上がりに嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "絞った後の湿ったタオル", "極上のバスローブ",
                    "Happy things after getting out of the bath",
                    "Not happy at all", "Absolute bliss",
                    "A wrung-out still-damp towel", "An ultra-luxurious bathrobe"),
                // 96
                new("寝坊した朝に助かるもの・こと",
                    "全然助からない", "間に合ってしまう",
                    "渋滞情報が酷いニュース", "ちょうどテレワークの日",
                    "Things that help when you've overslept",
                    "No help at all", "Somehow still make it",
                    "News that traffic is absolutely terrible", "Finding out it happens to be a work-from-home day"),
                // 97
                new("お正月に嬉しいもの・こと",
                    "全然嬉しくない", "最高に幸せ",
                    "年明け一番の税金通知", "親戚全員からのお年玉",
                    "Happy things about New Year",
                    "Not happy at all", "Pure happiness",
                    "A tax notice as the very first thing of the new year", "New Year's money from every single relative"),
                // 98
                new("冬のデートで楽しいもの・場所",
                    "全然楽しくない", "一生の思い出",
                    "駅前で凍えながら立ち話", "二人だけの秘密の夜景",
                    "Fun things or places for a winter date",
                    "Not fun at all", "A memory for life",
                    "Shivering through a conversation in front of the station", "A secret night view spot just for the two of you"),
                // 99
                new("大切な人への気持ちを伝えるもの・方法",
                    "全然伝わらない", "完璧に伝わる",
                    "レシートをそっと手渡す", "記念日に書いた長い手紙",
                    "Ways to express your feelings to someone special",
                    "Feeling not conveyed at all", "Perfectly understood",
                    "Quietly slipping them a receipt", "A long letter written on your anniversary"),
                // 100
                new("人生を振り返って一番嬉しかった体験",
                    "全く嬉しくなかった", "最高に嬉しかった",
                    "財布の隅の小銭を発見", "子どもが結婚した日の涙",
                    "The happiest experience when you look back on life",
                    "Not happy at all", "The greatest joy in life",
                    "Finding a few coins in the corner of your wallet", "The tears on the day your child got married"),
            };
        }
    }
}
